// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AcaProduct
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "aca")]
        #pragma warning disable CS1591
        Aca,
        #pragma warning restore CS1591
    }
}
