// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApplicantInput : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The age property</summary>
        public int? Age { get; set; }
        /// <summary>The blind_or_disabled property</summary>
        public bool? BlindOrDisabled { get; set; }
        /// <summary>The date_of_birth property</summary>
        public Date? DateOfBirth { get; set; }
        /// <summary>Optional applicant gender for quote flows that use gender in marketplace screening.</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicantInputGender? Gender { get; set; }
        /// <summary>Caller-supplied applicant identifier. Use a stable value from your system, such as `applicant-1`; this is not the applicant relationship. Send `relationship` separately as `primary`, `spouse`, or `dependent`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MemberId { get; set; }
#nullable restore
#else
        public string MemberId { get; set; }
#endif
        /// <summary>The native_american property</summary>
        public bool? NativeAmerican { get; set; }
        /// <summary>The pregnant property</summary>
        public bool? Pregnant { get; set; }
        /// <summary>The relationship property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicantInputRelationship? Relationship { get; set; }
        /// <summary>The uses_tobacco property</summary>
        public bool? UsesTobacco { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicantInput"/> and sets the default values.
        /// </summary>
        public ApplicantInput()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicantInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicantInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicantInput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "age", n => { Age = n.GetIntValue(); } },
                { "blind_or_disabled", n => { BlindOrDisabled = n.GetBoolValue(); } },
                { "date_of_birth", n => { DateOfBirth = n.GetDateValue(); } },
                { "gender", n => { Gender = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicantInputGender>(); } },
                { "member_id", n => { MemberId = n.GetStringValue(); } },
                { "native_american", n => { NativeAmerican = n.GetBoolValue(); } },
                { "pregnant", n => { Pregnant = n.GetBoolValue(); } },
                { "relationship", n => { Relationship = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicantInputRelationship>(); } },
                { "uses_tobacco", n => { UsesTobacco = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("age", Age);
            writer.WriteBoolValue("blind_or_disabled", BlindOrDisabled);
            writer.WriteDateValue("date_of_birth", DateOfBirth);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicantInputGender>("gender", Gender);
            writer.WriteStringValue("member_id", MemberId);
            writer.WriteBoolValue("native_american", NativeAmerican);
            writer.WriteBoolValue("pregnant", Pregnant);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicantInputRelationship>("relationship", Relationship);
            writer.WriteBoolValue("uses_tobacco", UsesTobacco);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
