// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>
    /// Carrier-reported payment status. Only present after submission; redirect carriers may not report it immediately.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApplicationResponsePayment : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The autopay_indicator property</summary>
        public bool? AutopayIndicator { get; set; }
        /// <summary>The current_member_responsibility_balance_due property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrentMemberResponsibilityBalanceDue { get; set; }
#nullable restore
#else
        public string CurrentMemberResponsibilityBalanceDue { get; set; }
#endif
        /// <summary>The grace_period_start_date property</summary>
        public Date? GracePeriodStartDate { get; set; }
        /// <summary>The paid_through_date property</summary>
        public Date? PaidThroughDate { get; set; }
        /// <summary>The past_due_member_responsibility_balance_due property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PastDueMemberResponsibilityBalanceDue { get; set; }
#nullable restore
#else
        public string PastDueMemberResponsibilityBalanceDue { get; set; }
#endif
        /// <summary>The payment_status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentStatus { get; set; }
#nullable restore
#else
        public string PaymentStatus { get; set; }
#endif
        /// <summary>The payment_status_updated_date property</summary>
        public Date? PaymentStatusUpdatedDate { get; set; }
        /// <summary>Union discriminator</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationResponsePayment"/> and sets the default values.
        /// </summary>
        public ApplicationResponsePayment()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationResponsePayment"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationResponsePayment CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationResponsePayment();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autopay_indicator", n => { AutopayIndicator = n.GetBoolValue(); } },
                { "current_member_responsibility_balance_due", n => { CurrentMemberResponsibilityBalanceDue = n.GetStringValue(); } },
                { "grace_period_start_date", n => { GracePeriodStartDate = n.GetDateValue(); } },
                { "paid_through_date", n => { PaidThroughDate = n.GetDateValue(); } },
                { "past_due_member_responsibility_balance_due", n => { PastDueMemberResponsibilityBalanceDue = n.GetStringValue(); } },
                { "payment_status", n => { PaymentStatus = n.GetStringValue(); } },
                { "payment_status_updated_date", n => { PaymentStatusUpdatedDate = n.GetDateValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("autopay_indicator", AutopayIndicator);
            writer.WriteStringValue("current_member_responsibility_balance_due", CurrentMemberResponsibilityBalanceDue);
            writer.WriteDateValue("grace_period_start_date", GracePeriodStartDate);
            writer.WriteDateValue("paid_through_date", PaidThroughDate);
            writer.WriteStringValue("past_due_member_responsibility_balance_due", PastDueMemberResponsibilityBalanceDue);
            writer.WriteStringValue("payment_status", PaymentStatus);
            writer.WriteDateValue("payment_status_updated_date", PaymentStatusUpdatedDate);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
