// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApplicationEvent : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The carrier_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CarrierId { get; set; }
#nullable restore
#else
        public string CarrierId { get; set; }
#endif
        /// <summary>Field-level changes. Sensitive fields such as SSN and ITIN are redacted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationEventChangesItem>? Changes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationEventChangesItem> Changes { get; set; }
#endif
        /// <summary>The effective_date property</summary>
        public Date? EffectiveDate { get; set; }
        /// <summary>&quot;For applicant change events: member id of the affected applicant.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MemberId { get; set; }
#nullable restore
#else
        public string MemberId { get; set; }
#endif
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The new_status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NewStatus { get; set; }
#nullable restore
#else
        public string NewStatus { get; set; }
#endif
        /// <summary>The occurred_at property</summary>
        public DateTimeOffset? OccurredAt { get; set; }
        /// <summary>The old_status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OldStatus { get; set; }
#nullable restore
#else
        public string OldStatus { get; set; }
#endif
        /// <summary>The policy_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PolicyId { get; set; }
#nullable restore
#else
        public string PolicyId { get; set; }
#endif
        /// <summary>The response_code property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResponseCode { get; set; }
#nullable restore
#else
        public string ResponseCode { get; set; }
#endif
        /// <summary>&quot;For `changed` events: whether the change was on the application or an applicant record.&quot;</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationEventTarget? Target { get; set; }
        /// <summary>The type property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationEventType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationEvent"/> and sets the default values.
        /// </summary>
        public ApplicationEvent()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationEvent"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationEvent CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationEvent();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "carrier_id", n => { CarrierId = n.GetStringValue(); } },
                { "changes", n => { Changes = n.GetCollectionOfObjectValues<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationEventChangesItem>(global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationEventChangesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "effective_date", n => { EffectiveDate = n.GetDateValue(); } },
                { "member_id", n => { MemberId = n.GetStringValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "new_status", n => { NewStatus = n.GetStringValue(); } },
                { "occurred_at", n => { OccurredAt = n.GetDateTimeOffsetValue(); } },
                { "old_status", n => { OldStatus = n.GetStringValue(); } },
                { "policy_id", n => { PolicyId = n.GetStringValue(); } },
                { "response_code", n => { ResponseCode = n.GetStringValue(); } },
                { "target", n => { Target = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationEventTarget>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationEventType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("carrier_id", CarrierId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationEventChangesItem>("changes", Changes);
            writer.WriteDateValue("effective_date", EffectiveDate);
            writer.WriteStringValue("member_id", MemberId);
            writer.WriteStringValue("message", Message);
            writer.WriteStringValue("new_status", NewStatus);
            writer.WriteDateTimeOffsetValue("occurred_at", OccurredAt);
            writer.WriteStringValue("old_status", OldStatus);
            writer.WriteStringValue("policy_id", PolicyId);
            writer.WriteStringValue("response_code", ResponseCode);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationEventTarget>("target", Target);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationEventType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
