// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>&quot;For `changed` events: whether the change was on the application or an applicant record.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ApplicationEventTarget
    {
        [EnumMember(Value = "application")]
        #pragma warning disable CS1591
        Application,
        #pragma warning restore CS1591
        [EnumMember(Value = "applicant")]
        #pragma warning disable CS1591
        Applicant,
        #pragma warning restore CS1591
    }
}
