// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ApplicantLanguage
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "english")]
        #pragma warning disable CS1591
        English,
        #pragma warning restore CS1591
        [EnumMember(Value = "spanish")]
        #pragma warning disable CS1591
        Spanish,
        #pragma warning restore CS1591
        [EnumMember(Value = "arabic")]
        #pragma warning disable CS1591
        Arabic,
        #pragma warning restore CS1591
        [EnumMember(Value = "chinese")]
        #pragma warning disable CS1591
        Chinese,
        #pragma warning restore CS1591
        [EnumMember(Value = "french_creole")]
        #pragma warning disable CS1591
        FrenchCreole,
        #pragma warning restore CS1591
        [EnumMember(Value = "french")]
        #pragma warning disable CS1591
        French,
        #pragma warning restore CS1591
        [EnumMember(Value = "german")]
        #pragma warning disable CS1591
        German,
        #pragma warning restore CS1591
        [EnumMember(Value = "gujarati")]
        #pragma warning disable CS1591
        Gujarati,
        #pragma warning restore CS1591
        [EnumMember(Value = "hindi")]
        #pragma warning disable CS1591
        Hindi,
        #pragma warning restore CS1591
        [EnumMember(Value = "korean")]
        #pragma warning disable CS1591
        Korean,
        #pragma warning restore CS1591
        [EnumMember(Value = "polish")]
        #pragma warning disable CS1591
        Polish,
        #pragma warning restore CS1591
        [EnumMember(Value = "portuguese")]
        #pragma warning disable CS1591
        Portuguese,
        #pragma warning restore CS1591
        [EnumMember(Value = "russian")]
        #pragma warning disable CS1591
        Russian,
        #pragma warning restore CS1591
        [EnumMember(Value = "tagalog")]
        #pragma warning disable CS1591
        Tagalog,
        #pragma warning restore CS1591
        [EnumMember(Value = "urdu")]
        #pragma warning disable CS1591
        Urdu,
        #pragma warning restore CS1591
        [EnumMember(Value = "vietnamese")]
        #pragma warning disable CS1591
        Vietnamese,
        #pragma warning restore CS1591
        [EnumMember(Value = "other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
    }
}
