// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ApplicantInputRelationship
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "primary")]
        #pragma warning disable CS1591
        Primary,
        #pragma warning restore CS1591
        [EnumMember(Value = "spouse")]
        #pragma warning disable CS1591
        Spouse,
        #pragma warning restore CS1591
        [EnumMember(Value = "dependent")]
        #pragma warning disable CS1591
        Dependent,
        #pragma warning restore CS1591
    }
}
