// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>Optional applicant gender for quote flows that use gender in marketplace screening.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ApplicantInputGender
    {
        [EnumMember(Value = "female")]
        #pragma warning disable CS1591
        Female,
        #pragma warning restore CS1591
        [EnumMember(Value = "male")]
        #pragma warning disable CS1591
        Male,
        #pragma warning restore CS1591
        [EnumMember(Value = "other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
    }
}
