// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ApplicationEventType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "submitted")]
        #pragma warning disable CS1591
        Submitted,
        #pragma warning restore CS1591
        [EnumMember(Value = "changed")]
        #pragma warning disable CS1591
        Changed,
        #pragma warning restore CS1591
        [EnumMember(Value = "document_status_changed")]
        #pragma warning disable CS1591
        DocumentStatusChanged,
        #pragma warning restore CS1591
        [EnumMember(Value = "cancelled")]
        #pragma warning disable CS1591
        Cancelled,
        #pragma warning restore CS1591
        [EnumMember(Value = "submission_failed")]
        #pragma warning disable CS1591
        SubmissionFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "policy_status_updated")]
        #pragma warning disable CS1591
        PolicyStatusUpdated,
        #pragma warning restore CS1591
    }
}
