// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>Pediatric dental attestation. `purchased_separately`: pediatric dental purchased via stand-alone dental plan. `not_applicable`: no children under 19 on the application.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AttestationsPediatricDental
    {
        [EnumMember(Value = "purchased_separately")]
        #pragma warning disable CS1591
        PurchasedSeparately,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_applicable")]
        #pragma warning disable CS1591
        NotApplicable,
        #pragma warning restore CS1591
    }
}
