// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Attestations : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The agent_advised_consumer_of_product_features property</summary>
        public bool? AgentAdvisedConsumerOfProductFeatures { get; set; }
        /// <summary>The agent_provided_consumer_marketing_materials property</summary>
        public bool? AgentProvidedConsumerMarketingMaterials { get; set; }
        /// <summary>The agent_retained_signed_application_copy property</summary>
        public bool? AgentRetainedSignedApplicationCopy { get; set; }
        /// <summary>The agent_submitted_application property</summary>
        public bool? AgentSubmittedApplication { get; set; }
        /// <summary>The agrees_issuer_attestations property</summary>
        public bool? AgreesIssuerAttestations { get; set; }
        /// <summary>The broker_signature_attestation property</summary>
        public bool? BrokerSignatureAttestation { get; set; }
        /// <summary>The consumer_working_with_agent property</summary>
        public bool? ConsumerWorkingWithAgent { get; set; }
        /// <summary>The coverage_replacement_attestation_accepted property</summary>
        public bool? CoverageReplacementAttestationAccepted { get; set; }
        /// <summary>The disclosure_statement_accepted property</summary>
        public bool? DisclosureStatementAccepted { get; set; }
        /// <summary>The electronic_signature_consent property</summary>
        public bool? ElectronicSignatureConsent { get; set; }
        /// <summary>&quot;Pediatric dental attestation. `purchased_separately`: pediatric dental purchased via stand-alone dental plan. `not_applicable`: no children under 19 on the application.&quot;</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.AttestationsPediatricDental? PediatricDental { get; set; }
        /// <summary>Authorization for dependents/spouse to be included on the application.</summary>
        public bool? SpouseOrDependentAuthorization { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.Attestations"/> and sets the default values.
        /// </summary>
        public Attestations()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.Attestations"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.Attestations CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.Attestations();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agent_advised_consumer_of_product_features", n => { AgentAdvisedConsumerOfProductFeatures = n.GetBoolValue(); } },
                { "agent_provided_consumer_marketing_materials", n => { AgentProvidedConsumerMarketingMaterials = n.GetBoolValue(); } },
                { "agent_retained_signed_application_copy", n => { AgentRetainedSignedApplicationCopy = n.GetBoolValue(); } },
                { "agent_submitted_application", n => { AgentSubmittedApplication = n.GetBoolValue(); } },
                { "agrees_issuer_attestations", n => { AgreesIssuerAttestations = n.GetBoolValue(); } },
                { "broker_signature_attestation", n => { BrokerSignatureAttestation = n.GetBoolValue(); } },
                { "consumer_working_with_agent", n => { ConsumerWorkingWithAgent = n.GetBoolValue(); } },
                { "coverage_replacement_attestation_accepted", n => { CoverageReplacementAttestationAccepted = n.GetBoolValue(); } },
                { "disclosure_statement_accepted", n => { DisclosureStatementAccepted = n.GetBoolValue(); } },
                { "electronic_signature_consent", n => { ElectronicSignatureConsent = n.GetBoolValue(); } },
                { "pediatric_dental", n => { PediatricDental = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.AttestationsPediatricDental>(); } },
                { "spouse_or_dependent_authorization", n => { SpouseOrDependentAuthorization = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("agent_advised_consumer_of_product_features", AgentAdvisedConsumerOfProductFeatures);
            writer.WriteBoolValue("agent_provided_consumer_marketing_materials", AgentProvidedConsumerMarketingMaterials);
            writer.WriteBoolValue("agent_retained_signed_application_copy", AgentRetainedSignedApplicationCopy);
            writer.WriteBoolValue("agent_submitted_application", AgentSubmittedApplication);
            writer.WriteBoolValue("agrees_issuer_attestations", AgreesIssuerAttestations);
            writer.WriteBoolValue("broker_signature_attestation", BrokerSignatureAttestation);
            writer.WriteBoolValue("consumer_working_with_agent", ConsumerWorkingWithAgent);
            writer.WriteBoolValue("coverage_replacement_attestation_accepted", CoverageReplacementAttestationAccepted);
            writer.WriteBoolValue("disclosure_statement_accepted", DisclosureStatementAccepted);
            writer.WriteBoolValue("electronic_signature_consent", ElectronicSignatureConsent);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.AttestationsPediatricDental>("pediatric_dental", PediatricDental);
            writer.WriteBoolValue("spouse_or_dependent_authorization", SpouseOrDependentAuthorization);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
