// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CommunicationPreferences : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The agrees_hsa_contact_opt_in property</summary>
        public bool? AgreesHsaContactOptIn { get; set; }
        /// <summary>The application_notification_call property</summary>
        public bool? ApplicationNotificationCall { get; set; }
        /// <summary>The application_notification_email property</summary>
        public bool? ApplicationNotificationEmail { get; set; }
        /// <summary>The application_notification_text property</summary>
        public bool? ApplicationNotificationText { get; set; }
        /// <summary>Whether the applicant has affirmed their communication preferences.</summary>
        public bool? CommunicationPreferenceAffirmed { get; set; }
        /// <summary>The decline_marketing_contact property</summary>
        public bool? DeclineMarketingContact { get; set; }
        /// <summary>The email_contact_consent property</summary>
        public bool? EmailContactConsent { get; set; }
        /// <summary>The marketing_contact_consent property</summary>
        public bool? MarketingContactConsent { get; set; }
        /// <summary>The preferred_communication_method property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.CommunicationPreferencesPreferredCommunicationMethod? PreferredCommunicationMethod { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.CommunicationPreferences"/> and sets the default values.
        /// </summary>
        public CommunicationPreferences()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.CommunicationPreferences"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.CommunicationPreferences CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.CommunicationPreferences();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agrees_hsa_contact_opt_in", n => { AgreesHsaContactOptIn = n.GetBoolValue(); } },
                { "application_notification_call", n => { ApplicationNotificationCall = n.GetBoolValue(); } },
                { "application_notification_email", n => { ApplicationNotificationEmail = n.GetBoolValue(); } },
                { "application_notification_text", n => { ApplicationNotificationText = n.GetBoolValue(); } },
                { "communication_preference_affirmed", n => { CommunicationPreferenceAffirmed = n.GetBoolValue(); } },
                { "decline_marketing_contact", n => { DeclineMarketingContact = n.GetBoolValue(); } },
                { "email_contact_consent", n => { EmailContactConsent = n.GetBoolValue(); } },
                { "marketing_contact_consent", n => { MarketingContactConsent = n.GetBoolValue(); } },
                { "preferred_communication_method", n => { PreferredCommunicationMethod = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.CommunicationPreferencesPreferredCommunicationMethod>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("agrees_hsa_contact_opt_in", AgreesHsaContactOptIn);
            writer.WriteBoolValue("application_notification_call", ApplicationNotificationCall);
            writer.WriteBoolValue("application_notification_email", ApplicationNotificationEmail);
            writer.WriteBoolValue("application_notification_text", ApplicationNotificationText);
            writer.WriteBoolValue("communication_preference_affirmed", CommunicationPreferenceAffirmed);
            writer.WriteBoolValue("decline_marketing_contact", DeclineMarketingContact);
            writer.WriteBoolValue("email_contact_consent", EmailContactConsent);
            writer.WriteBoolValue("marketing_contact_consent", MarketingContactConsent);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.CommunicationPreferencesPreferredCommunicationMethod>("preferred_communication_method", PreferredCommunicationMethod);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
