// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DentalFilters : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The adult_coverage property</summary>
        public bool? AdultCoverage { get; set; }
        /// <summary>The annual_maximum_min property</summary>
        public double? AnnualMaximumMin { get; set; }
        /// <summary>The child_coverage property</summary>
        public bool? ChildCoverage { get; set; }
        /// <summary>The metal_levels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HealthSherpa.OpenApiClient.Models.DentalFiltersMetalLevelsItem?>? MetalLevels { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HealthSherpa.OpenApiClient.Models.DentalFiltersMetalLevelsItem?> MetalLevels { get; set; }
#endif
        /// <summary>The orthodontia_coverage property</summary>
        public bool? OrthodontiaCoverage { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.DentalFilters"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.DentalFilters CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.DentalFilters();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "adult_coverage", n => { AdultCoverage = n.GetBoolValue(); } },
                { "annual_maximum_min", n => { AnnualMaximumMin = n.GetDoubleValue(); } },
                { "child_coverage", n => { ChildCoverage = n.GetBoolValue(); } },
                { "metal_levels", n => { MetalLevels = n.GetCollectionOfEnumValues<global::Soenneker.HealthSherpa.OpenApiClient.Models.DentalFiltersMetalLevelsItem>()?.AsList(); } },
                { "orthodontia_coverage", n => { OrthodontiaCoverage = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("adult_coverage", AdultCoverage);
            writer.WriteDoubleValue("annual_maximum_min", AnnualMaximumMin);
            writer.WriteBoolValue("child_coverage", ChildCoverage);
            writer.WriteCollectionOfEnumValues<global::Soenneker.HealthSherpa.OpenApiClient.Models.DentalFiltersMetalLevelsItem>("metal_levels", MetalLevels);
            writer.WriteBoolValue("orthodontia_coverage", OrthodontiaCoverage);
        }
    }
}
#pragma warning restore CS0618
