// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Dependent : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether the applicant wants to be added to the Donate Life registry. Only accepted by carriers that support this field.</summary>
        public bool? AddToDonateLifeRegistry { get; set; }
        /// <summary>Address for a dependent living at a different address than the primary applicant.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.AlternateAddress? AlternateAddress { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.AlternateAddress AlternateAddress { get; set; }
#endif
        /// <summary>The currently_incarcerated property</summary>
        public bool? CurrentlyIncarcerated { get; set; }
        /// <summary>The date_of_birth property</summary>
        public Date? DateOfBirth { get; set; }
        /// <summary>Expected end date of a temporary disability. Only accepted by carriers that require disability follow-up questions.</summary>
        public Date? DisabilityEndDate { get; set; }
        /// <summary>Whether the disability is temporary. Only accepted by carriers that require disability follow-up questions.</summary>
        public bool? DisabilityIsTemporary { get; set; }
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The enrolled_in_medicaid_chip_or_other_gov_program property</summary>
        public bool? EnrolledInMedicaidChipOrOtherGovProgram { get; set; }
        /// <summary>The enrolled_in_medicare property</summary>
        public bool? EnrolledInMedicare { get; set; }
        /// <summary>The enrolled_in_medicare_parts_a_or_b property</summary>
        public bool? EnrolledInMedicarePartsAOrB { get; set; }
        /// <summary>The existing_coverage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.ExistingCoverage? ExistingCoverage { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.ExistingCoverage ExistingCoverage { get; set; }
#endif
        /// <summary>Your identifier for this member.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalId { get; set; }
#nullable restore
#else
        public string ExternalId { get; set; }
#endif
        /// <summary>The first_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>The full_time_student property</summary>
        public bool? FullTimeStudent { get; set; }
        /// <summary>`male` and `female` are accepted by all carriers. `x` is accepted for New York applicants; carriers in other states reject `x` at submission.</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PrimaryApplicantGender? Gender { get; set; }
        /// <summary>Required if `full_time_student` is `true`.</summary>
        public Date? GraduationDate { get; set; }
        /// <summary>Required for primary applicants under 18.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.Guardian? Guardian { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.Guardian Guardian { get; set; }
#endif
        /// <summary>Affects dependent age eligibility limits.</summary>
        public bool? HasDisability { get; set; }
        /// <summary>The has_eligible_immigration_status property</summary>
        public bool? HasEligibleImmigrationStatus { get; set; }
        /// <summary>Required by some carriers. Use `decline_to_answer` if not collected.</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PrimaryApplicantHispanicOrigin? HispanicOrigin { get; set; }
        /// <summary>Required when `hispanic_origin` is `yes`.</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PrimaryApplicantHispanicOriginDescription? HispanicOriginDescription { get; set; }
        /// <summary>Individual Taxpayer Identification Number. Alternative to SSN.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Itin { get; set; }
#nullable restore
#else
        public string Itin { get; set; }
#endif
        /// <summary>The language_spoken property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicantLanguage? LanguageSpoken { get; set; }
        /// <summary>The language_written property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicantLanguage? LanguageWritten { get; set; }
        /// <summary>The last_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>Carrier-specific marital status. When provided, takes precedence over the `married` boolean.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaritalStatus { get; set; }
#nullable restore
#else
        public string MaritalStatus { get; set; }
#endif
        /// <summary>The married property</summary>
        public bool? Married { get; set; }
        /// <summary>Whether the applicant is eligible for Medicare.</summary>
        public bool? MedicareEligible { get; set; }
        /// <summary>Whether the applicant is eligible for Medicare or Medicaid. Only accepted by carriers that require this field.</summary>
        public bool? MedicareMedicaidEligible { get; set; }
        /// <summary>The middle_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MiddleName { get; set; }
#nullable restore
#else
        public string MiddleName { get; set; }
#endif
        /// <summary>The phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Phone { get; set; }
#nullable restore
#else
        public string Phone { get; set; }
#endif
        /// <summary>Required by some carriers. Use `decline_to_answer` if not collected.</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PrimaryApplicantRaceEthnicity? RaceEthnicity { get; set; }
        /// <summary>`spouse`, `domestic_partner`, and `child` are supported by all carriers. Other values are accepted by select carriers and states.</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.DependentRelationship? Relationship { get; set; }
        /// <summary>The resides_in_state property</summary>
        public bool? ResidesInState { get; set; }
        /// <summary>9 digits, no dashes. Encrypted at rest.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Ssn { get; set; }
#nullable restore
#else
        public string Ssn { get; set; }
#endif
        /// <summary>The suffix property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PrimaryApplicantSuffix? Suffix { get; set; }
        /// <summary>Set to `true` if tobacco question is not applicable for this applicant.</summary>
        public bool? TobaccoNotApplicable { get; set; }
        /// <summary>The us_citizen property</summary>
        public bool? UsCitizen { get; set; }
        /// <summary>Tobacco use in the last 6 months.</summary>
        public bool? UsesTobacco { get; set; }
        /// <summary>The veteran_or_active_duty_military property</summary>
        public bool? VeteranOrActiveDutyMilitary { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.Dependent"/> and sets the default values.
        /// </summary>
        public Dependent()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.Dependent"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.Dependent CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.Dependent();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "add_to_donate_life_registry", n => { AddToDonateLifeRegistry = n.GetBoolValue(); } },
                { "alternate_address", n => { AlternateAddress = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.AlternateAddress>(global::Soenneker.HealthSherpa.OpenApiClient.Models.AlternateAddress.CreateFromDiscriminatorValue); } },
                { "currently_incarcerated", n => { CurrentlyIncarcerated = n.GetBoolValue(); } },
                { "date_of_birth", n => { DateOfBirth = n.GetDateValue(); } },
                { "disability_end_date", n => { DisabilityEndDate = n.GetDateValue(); } },
                { "disability_is_temporary", n => { DisabilityIsTemporary = n.GetBoolValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "enrolled_in_medicaid_chip_or_other_gov_program", n => { EnrolledInMedicaidChipOrOtherGovProgram = n.GetBoolValue(); } },
                { "enrolled_in_medicare", n => { EnrolledInMedicare = n.GetBoolValue(); } },
                { "enrolled_in_medicare_parts_a_or_b", n => { EnrolledInMedicarePartsAOrB = n.GetBoolValue(); } },
                { "existing_coverage", n => { ExistingCoverage = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.ExistingCoverage>(global::Soenneker.HealthSherpa.OpenApiClient.Models.ExistingCoverage.CreateFromDiscriminatorValue); } },
                { "external_id", n => { ExternalId = n.GetStringValue(); } },
                { "first_name", n => { FirstName = n.GetStringValue(); } },
                { "full_time_student", n => { FullTimeStudent = n.GetBoolValue(); } },
                { "gender", n => { Gender = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PrimaryApplicantGender>(); } },
                { "graduation_date", n => { GraduationDate = n.GetDateValue(); } },
                { "guardian", n => { Guardian = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.Guardian>(global::Soenneker.HealthSherpa.OpenApiClient.Models.Guardian.CreateFromDiscriminatorValue); } },
                { "has_disability", n => { HasDisability = n.GetBoolValue(); } },
                { "has_eligible_immigration_status", n => { HasEligibleImmigrationStatus = n.GetBoolValue(); } },
                { "hispanic_origin", n => { HispanicOrigin = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PrimaryApplicantHispanicOrigin>(); } },
                { "hispanic_origin_description", n => { HispanicOriginDescription = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PrimaryApplicantHispanicOriginDescription>(); } },
                { "itin", n => { Itin = n.GetStringValue(); } },
                { "language_spoken", n => { LanguageSpoken = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicantLanguage>(); } },
                { "language_written", n => { LanguageWritten = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicantLanguage>(); } },
                { "last_name", n => { LastName = n.GetStringValue(); } },
                { "marital_status", n => { MaritalStatus = n.GetStringValue(); } },
                { "married", n => { Married = n.GetBoolValue(); } },
                { "medicare_eligible", n => { MedicareEligible = n.GetBoolValue(); } },
                { "medicare_medicaid_eligible", n => { MedicareMedicaidEligible = n.GetBoolValue(); } },
                { "middle_name", n => { MiddleName = n.GetStringValue(); } },
                { "phone", n => { Phone = n.GetStringValue(); } },
                { "race_ethnicity", n => { RaceEthnicity = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PrimaryApplicantRaceEthnicity>(); } },
                { "relationship", n => { Relationship = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.DependentRelationship>(); } },
                { "resides_in_state", n => { ResidesInState = n.GetBoolValue(); } },
                { "ssn", n => { Ssn = n.GetStringValue(); } },
                { "suffix", n => { Suffix = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PrimaryApplicantSuffix>(); } },
                { "tobacco_not_applicable", n => { TobaccoNotApplicable = n.GetBoolValue(); } },
                { "us_citizen", n => { UsCitizen = n.GetBoolValue(); } },
                { "uses_tobacco", n => { UsesTobacco = n.GetBoolValue(); } },
                { "veteran_or_active_duty_military", n => { VeteranOrActiveDutyMilitary = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("add_to_donate_life_registry", AddToDonateLifeRegistry);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.AlternateAddress>("alternate_address", AlternateAddress);
            writer.WriteBoolValue("currently_incarcerated", CurrentlyIncarcerated);
            writer.WriteDateValue("date_of_birth", DateOfBirth);
            writer.WriteDateValue("disability_end_date", DisabilityEndDate);
            writer.WriteBoolValue("disability_is_temporary", DisabilityIsTemporary);
            writer.WriteStringValue("email", Email);
            writer.WriteBoolValue("enrolled_in_medicaid_chip_or_other_gov_program", EnrolledInMedicaidChipOrOtherGovProgram);
            writer.WriteBoolValue("enrolled_in_medicare", EnrolledInMedicare);
            writer.WriteBoolValue("enrolled_in_medicare_parts_a_or_b", EnrolledInMedicarePartsAOrB);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.ExistingCoverage>("existing_coverage", ExistingCoverage);
            writer.WriteStringValue("external_id", ExternalId);
            writer.WriteStringValue("first_name", FirstName);
            writer.WriteBoolValue("full_time_student", FullTimeStudent);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PrimaryApplicantGender>("gender", Gender);
            writer.WriteDateValue("graduation_date", GraduationDate);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.Guardian>("guardian", Guardian);
            writer.WriteBoolValue("has_disability", HasDisability);
            writer.WriteBoolValue("has_eligible_immigration_status", HasEligibleImmigrationStatus);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PrimaryApplicantHispanicOrigin>("hispanic_origin", HispanicOrigin);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PrimaryApplicantHispanicOriginDescription>("hispanic_origin_description", HispanicOriginDescription);
            writer.WriteStringValue("itin", Itin);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicantLanguage>("language_spoken", LanguageSpoken);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicantLanguage>("language_written", LanguageWritten);
            writer.WriteStringValue("last_name", LastName);
            writer.WriteStringValue("marital_status", MaritalStatus);
            writer.WriteBoolValue("married", Married);
            writer.WriteBoolValue("medicare_eligible", MedicareEligible);
            writer.WriteBoolValue("medicare_medicaid_eligible", MedicareMedicaidEligible);
            writer.WriteStringValue("middle_name", MiddleName);
            writer.WriteStringValue("phone", Phone);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PrimaryApplicantRaceEthnicity>("race_ethnicity", RaceEthnicity);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.DependentRelationship>("relationship", Relationship);
            writer.WriteBoolValue("resides_in_state", ResidesInState);
            writer.WriteStringValue("ssn", Ssn);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PrimaryApplicantSuffix>("suffix", Suffix);
            writer.WriteBoolValue("tobacco_not_applicable", TobaccoNotApplicable);
            writer.WriteBoolValue("us_citizen", UsCitizen);
            writer.WriteBoolValue("uses_tobacco", UsesTobacco);
            writer.WriteBoolValue("veteran_or_active_duty_military", VeteranOrActiveDutyMilitary);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
