// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>
    /// HealthSherpa ONE direct enrollment create request. Send the application payload at the request root and include the HealthSherpa ONE `context` object for routing. HealthSherpa ONE uses `context` only for routing and applies the agent and TPA identifiers (`_agent_id`, `tpa_slug`) from your approved account setup; caller-supplied `_agent_id`, `tpa_slug`, `actor.agent_id`, and `agent_of_record` are rejected.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EnrollmentRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Server-owned HealthSherpa agent identifier. Do not send this field; caller-supplied values return `400 invalid_request`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AgentId { get; set; }
#nullable restore
#else
        public string AgentId { get; set; }
#endif
        /// <summary>Agent-of-record payload. HealthSherpa ONE does not accept caller-supplied agent-of-record data on `POST /v1/enrollments`; attribution is derived from your approved account setup.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.AgentOfRecord? AgentOfRecord { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.AgentOfRecord AgentOfRecord { get; set; }
#endif
        /// <summary>The american_indian_or_alaskan_native_in_household property</summary>
        public bool? AmericanIndianOrAlaskanNativeInHousehold { get; set; }
        /// <summary>Optional tracking and attribution parameters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.Analytics? Analytics { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.Analytics Analytics { get; set; }
#endif
        /// <summary>The applicants property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.Applicants? Applicants { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.Applicants Applicants { get; set; }
#endif
        /// <summary>The attestations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.Attestations? Attestations { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.Attestations Attestations { get; set; }
#endif
        /// <summary>The communication_preferences property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.CommunicationPreferences? CommunicationPreferences { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.CommunicationPreferences CommunicationPreferences { get; set; }
#endif
        /// <summary>Routing context for direct enrollment create requests. Direct enrollment currently supports only `product = ichra` and `exchange = off_exchange`. Use `POST /v1/enrollment-sessions` for on-exchange enrollment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentContext? Context { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentContext Context { get; set; }
#endif
        /// <summary>Optional. When omitted, the carrier auto-determines the effective date based on the SEP type and event date. When provided, the date must be valid for the SEP reason and event date. Invalid dates return `422` with valid choices when available, or a message that effective-date selection is unavailable. There is no endpoint to query valid dates ahead of time.</summary>
        public Date? DesiredEffectiveDate { get; set; }
        /// <summary>Your unique identifier for this application. When omitted, HealthSherpa ONE defaults it to the request&apos;s `Idempotency-Key`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalId { get; set; }
#nullable restore
#else
        public string ExternalId { get; set; }
#endif
        /// <summary>Health Reimbursement Arrangement details. Applies to the primary applicant, the employee receiving the HRA offer. If the ICHRA is affordable, all household members are ineligible for premium tax credits.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.Hra? Hra { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.Hra Hra { get; set; }
#endif
        /// <summary>The mailing_address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.MailingAddress? MailingAddress { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.MailingAddress MailingAddress { get; set; }
#endif
        /// <summary>14-character HIOS plan ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlanHiosId { get; set; }
#nullable restore
#else
        public string PlanHiosId { get; set; }
#endif
        /// <summary>Plan year for the application. Omit this root field; HealthSherpa ONE sets it from `context.plan_year`.</summary>
        public int? PlanYear { get; set; }
        /// <summary>The residential_address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.Address? ResidentialAddress { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.Address ResidentialAddress { get; set; }
#endif
        /// <summary>The signatures property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.Signatures? Signatures { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.Signatures Signatures { get; set; }
#endif
        /// <summary>The special_enrollment_period property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.SpecialEnrollmentPeriod? SpecialEnrollmentPeriod { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.SpecialEnrollmentPeriod SpecialEnrollmentPeriod { get; set; }
#endif
        /// <summary>Server-owned HealthSherpa TPA identifier. Do not send this field; caller-supplied values return `400 invalid_request`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TpaSlug { get; set; }
#nullable restore
#else
        public string TpaSlug { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentRequest"/> and sets the default values.
        /// </summary>
        public EnrollmentRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "_agent_id", n => { AgentId = n.GetStringValue(); } },
                { "agent_of_record", n => { AgentOfRecord = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.AgentOfRecord>(global::Soenneker.HealthSherpa.OpenApiClient.Models.AgentOfRecord.CreateFromDiscriminatorValue); } },
                { "american_indian_or_alaskan_native_in_household", n => { AmericanIndianOrAlaskanNativeInHousehold = n.GetBoolValue(); } },
                { "analytics", n => { Analytics = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.Analytics>(global::Soenneker.HealthSherpa.OpenApiClient.Models.Analytics.CreateFromDiscriminatorValue); } },
                { "applicants", n => { Applicants = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.Applicants>(global::Soenneker.HealthSherpa.OpenApiClient.Models.Applicants.CreateFromDiscriminatorValue); } },
                { "attestations", n => { Attestations = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.Attestations>(global::Soenneker.HealthSherpa.OpenApiClient.Models.Attestations.CreateFromDiscriminatorValue); } },
                { "communication_preferences", n => { CommunicationPreferences = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.CommunicationPreferences>(global::Soenneker.HealthSherpa.OpenApiClient.Models.CommunicationPreferences.CreateFromDiscriminatorValue); } },
                { "context", n => { Context = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentContext>(global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentContext.CreateFromDiscriminatorValue); } },
                { "desired_effective_date", n => { DesiredEffectiveDate = n.GetDateValue(); } },
                { "external_id", n => { ExternalId = n.GetStringValue(); } },
                { "hra", n => { Hra = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.Hra>(global::Soenneker.HealthSherpa.OpenApiClient.Models.Hra.CreateFromDiscriminatorValue); } },
                { "mailing_address", n => { MailingAddress = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.MailingAddress>(global::Soenneker.HealthSherpa.OpenApiClient.Models.MailingAddress.CreateFromDiscriminatorValue); } },
                { "plan_hios_id", n => { PlanHiosId = n.GetStringValue(); } },
                { "plan_year", n => { PlanYear = n.GetIntValue(); } },
                { "residential_address", n => { ResidentialAddress = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.Address>(global::Soenneker.HealthSherpa.OpenApiClient.Models.Address.CreateFromDiscriminatorValue); } },
                { "signatures", n => { Signatures = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.Signatures>(global::Soenneker.HealthSherpa.OpenApiClient.Models.Signatures.CreateFromDiscriminatorValue); } },
                { "special_enrollment_period", n => { SpecialEnrollmentPeriod = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.SpecialEnrollmentPeriod>(global::Soenneker.HealthSherpa.OpenApiClient.Models.SpecialEnrollmentPeriod.CreateFromDiscriminatorValue); } },
                { "tpa_slug", n => { TpaSlug = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("_agent_id", AgentId);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.AgentOfRecord>("agent_of_record", AgentOfRecord);
            writer.WriteBoolValue("american_indian_or_alaskan_native_in_household", AmericanIndianOrAlaskanNativeInHousehold);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.Analytics>("analytics", Analytics);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.Applicants>("applicants", Applicants);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.Attestations>("attestations", Attestations);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.CommunicationPreferences>("communication_preferences", CommunicationPreferences);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentContext>("context", Context);
            writer.WriteDateValue("desired_effective_date", DesiredEffectiveDate);
            writer.WriteStringValue("external_id", ExternalId);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.Hra>("hra", Hra);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.MailingAddress>("mailing_address", MailingAddress);
            writer.WriteStringValue("plan_hios_id", PlanHiosId);
            writer.WriteIntValue("plan_year", PlanYear);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.Address>("residential_address", ResidentialAddress);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.Signatures>("signatures", Signatures);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.SpecialEnrollmentPeriod>("special_enrollment_period", SpecialEnrollmentPeriod);
            writer.WriteStringValue("tpa_slug", TpaSlug);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
