// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>`es-MX` enables the Spanish flow via the deep link&apos;s `ljs` parameter.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EnrollmentSessionContextLocale
    {
        [EnumMember(Value = "en-US")]
        #pragma warning disable CS1591
        EnUs,
        #pragma warning restore CS1591
        [EnumMember(Value = "es-MX")]
        #pragma warning disable CS1591
        EsMx,
        #pragma warning restore CS1591
    }
}
