// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>`draft` when the application has not yet been submitted. Transitions to `pending_effectuation` on successful submission. `submission_failed` means asynchronous carrier submission failed after submit returned.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EnrollmentResponsePolicyStatus
    {
        [EnumMember(Value = "draft")]
        #pragma warning disable CS1591
        Draft,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending_effectuation")]
        #pragma warning disable CS1591
        PendingEffectuation,
        #pragma warning restore CS1591
        [EnumMember(Value = "effectuated")]
        #pragma warning disable CS1591
        Effectuated,
        #pragma warning restore CS1591
        [EnumMember(Value = "submission_failed")]
        #pragma warning disable CS1591
        SubmissionFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "cancelled")]
        #pragma warning disable CS1591
        Cancelled,
        #pragma warning restore CS1591
        [EnumMember(Value = "terminated")]
        #pragma warning disable CS1591
        Terminated,
        #pragma warning restore CS1591
    }
}
