// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>SEP document verification status. `required` means documentation must be uploaded; `uploaded` means sent to carrier pending verification; `verified` means accepted; `denied` means carrier denied the documentation.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EnrollmentResponseDocumentStatus
    {
        [EnumMember(Value = "none_needed")]
        #pragma warning disable CS1591
        NoneNeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "required")]
        #pragma warning disable CS1591
        Required,
        #pragma warning restore CS1591
        [EnumMember(Value = "uploaded")]
        #pragma warning disable CS1591
        Uploaded,
        #pragma warning restore CS1591
        [EnumMember(Value = "verified")]
        #pragma warning disable CS1591
        Verified,
        #pragma warning restore CS1591
        [EnumMember(Value = "denied")]
        #pragma warning disable CS1591
        Denied,
        #pragma warning restore CS1591
    }
}
