// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EnrollmentSessionContext : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The coverage_family property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContextCoverageFamily? CoverageFamily { get; set; }
        /// <summary>The coverage_type property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContextCoverageType? CoverageType { get; set; }
        /// <summary>The exchange property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContextExchange? Exchange { get; set; }
        /// <summary>Mapped to the deep link&apos;s `user_type` (`agent_assisted` -&gt; `agent`, `self_service` -&gt; `consumer`).</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContextFlow? Flow { get; set; }
        /// <summary>`es-MX` enables the Spanish flow via the deep link&apos;s `ljs` parameter.</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContextLocale? Locale { get; set; }
        /// <summary>The plan_year property</summary>
        public int? PlanYear { get; set; }
        /// <summary>The product property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContextProduct? Product { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContext"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContext CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContext();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "coverage_family", n => { CoverageFamily = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContextCoverageFamily>(); } },
                { "coverage_type", n => { CoverageType = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContextCoverageType>(); } },
                { "exchange", n => { Exchange = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContextExchange>(); } },
                { "flow", n => { Flow = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContextFlow>(); } },
                { "locale", n => { Locale = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContextLocale>(); } },
                { "plan_year", n => { PlanYear = n.GetIntValue(); } },
                { "product", n => { Product = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContextProduct>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContextCoverageFamily>("coverage_family", CoverageFamily);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContextCoverageType>("coverage_type", CoverageType);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContextExchange>("exchange", Exchange);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContextFlow>("flow", Flow);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContextLocale>("locale", Locale);
            writer.WriteIntValue("plan_year", PlanYear);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContextProduct>("product", Product);
        }
    }
}
#pragma warning restore CS0618
