// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>Mapped to the deep link&apos;s `user_type` (`agent_assisted` -&gt; `agent`, `self_service` -&gt; `consumer`).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EnrollmentSessionContextFlow
    {
        [EnumMember(Value = "agent_assisted")]
        #pragma warning disable CS1591
        AgentAssisted,
        #pragma warning restore CS1591
        [EnumMember(Value = "self_service")]
        #pragma warning disable CS1591
        SelfService,
        #pragma warning restore CS1591
    }
}
