// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EnrollmentSessionEnrollmentHraFrequency
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "annually")]
        #pragma warning disable CS1591
        Annually,
        #pragma warning restore CS1591
        [EnumMember(Value = "monthly")]
        #pragma warning disable CS1591
        Monthly,
        #pragma warning restore CS1591
        [EnumMember(Value = "quarterly")]
        #pragma warning disable CS1591
        Quarterly,
        #pragma warning restore CS1591
        [EnumMember(Value = "one_time")]
        #pragma warning disable CS1591
        OneTime,
        #pragma warning restore CS1591
    }
}
