// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>
    /// POST /v1/enrollment-sessions request body. Unsupported fields anywhere in the body are rejected with `400 invalid_request`. In `self_service`, supply at least one of `location.state` or top-level `plan_id`. In `agent_assisted`, `location.state` is required and `plan_id` is not accepted.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EnrollmentSessionRequest : IParsable
    {
        /// <summary>&quot;Marketing attribution. Only accepted when `context.flow` is `self_service`; sending any field with `flow: \&quot;agent_assisted\&quot;` is rejected with `400 invalid_request`.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionCampaign? Campaign { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionCampaign Campaign { get; set; }
#endif
        /// <summary>&quot;DEPRECATED legacy contact block. Every property here has a 1:1 replacement on `household.applicants[]` and is preferred when both are supplied: `first_name` → `household.applicants[primary].first_name`, `last_name` → `household.applicants[primary].last_name`, `email` → `household.applicants[primary].email`, `phone_number` → `household.applicants[primary].phone_number`. Each field that is still supplied here surfaces a `deprecated_field` entry in the response&apos;s `warnings[]` array. The block remains accepted for backwards compatibility but may be removed at any time; migrate to the applicant-level fields.&quot;</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionClient? Client { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionClient Client { get; set; }
#endif
        /// <summary>The context property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContext? Context { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContext Context { get; set; }
#endif
        /// <summary>Accepts `hra`. Other enrollment subobjects (`special_enrollment_period`, `communication_preferences`) are not supported and are rejected with `400 invalid_request`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionEnrollment? Enrollment { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionEnrollment Enrollment { get; set; }
#endif
        /// <summary>Partner-supplied identifier echoed in the response and used for CRM correlation. Strongly recommended; must not contain PII.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalId { get; set; }
#nullable restore
#else
        public string ExternalId { get; set; }
#endif
        /// <summary>`household_size` must be at least 1. Applicants can include at most one `primary` and one `spouse`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionHousehold? Household { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionHousehold Household { get; set; }
#endif
        /// <summary>Routing geography plus optional street address. `zip_code`, `fips_code`, and `state` route the request; `address_line_1`, `address_line_2`, and `city` are used by the agent-assisted enrollment flow only and ignored on self-service deep links.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionLocation? Location { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionLocation Location { get; set; }
#endif
        /// <summary>Free-form note for the assisting agent. Used only in the agent-assisted enrollment flow; ignored on self-service deep links. Capped at 500 characters; longer values are rejected with `400 invalid_request`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>Plan ID (HIOS ID). Available only for the `self_service` flow, where it identifies the plan for the generated apply link. Invalid for `agent_assisted` — requests carrying `plan_id` with `context.flow` set to `agent_assisted` are rejected with `400 invalid_request`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlanId { get; set; }
#nullable restore
#else
        public string PlanId { get; set; }
#endif
        /// <summary>Provider identifiers (NPI strings) the household cares about. Used by the agent-assisted enrollment flow and added to the self-service `shopping_url` as a network filter (shop only; not added to `client_apply_url`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Providers { get; set; }
#nullable restore
#else
        public List<string> Providers { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "campaign", n => { Campaign = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionCampaign>(global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionCampaign.CreateFromDiscriminatorValue); } },
                { "client", n => { Client = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionClient>(global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionClient.CreateFromDiscriminatorValue); } },
                { "context", n => { Context = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContext>(global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContext.CreateFromDiscriminatorValue); } },
                { "enrollment", n => { Enrollment = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionEnrollment>(global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionEnrollment.CreateFromDiscriminatorValue); } },
                { "external_id", n => { ExternalId = n.GetStringValue(); } },
                { "household", n => { Household = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionHousehold>(global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionHousehold.CreateFromDiscriminatorValue); } },
                { "location", n => { Location = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionLocation>(global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionLocation.CreateFromDiscriminatorValue); } },
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "plan_id", n => { PlanId = n.GetStringValue(); } },
                { "providers", n => { Providers = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionCampaign>("campaign", Campaign);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionClient>("client", Client);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionContext>("context", Context);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionEnrollment>("enrollment", Enrollment);
            writer.WriteStringValue("external_id", ExternalId);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionHousehold>("household", Household);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionLocation>("location", Location);
            writer.WriteStringValue("notes", Notes);
            writer.WriteStringValue("plan_id", PlanId);
            writer.WriteCollectionOfPrimitiveValues<string>("providers", Providers);
        }
    }
}
#pragma warning restore CS0618
