// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>
    /// Successful direct enrollment application response. Successful responses can contain `errors[]` as submission-readiness data; error responses are documented separately under the `EnrollmentError` response.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EnrollmentResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Echo of the application data as stored.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentResponseApplication? Application { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentResponseApplication Application { get; set; }
#endif
        /// <summary>The application_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApplicationId { get; set; }
#nullable restore
#else
        public string ApplicationId { get; set; }
#endif
        /// <summary>Whether a plan change is currently allowed. Only present on submitted applications.</summary>
        public bool? CanChangePlan { get; set; }
        /// <summary>Whether demographic changes can be reported. Only present on submitted applications.</summary>
        public bool? CanReportChange { get; set; }
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The desired_effective_date property</summary>
        public Date? DesiredEffectiveDate { get; set; }
        /// <summary>SEP document verification status. `required` means documentation must be uploaded; `uploaded` means sent to carrier pending verification; `verified` means accepted; `denied` means carrier denied the documentation.</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentResponseDocumentStatus? DocumentStatus { get; set; }
        /// <summary>Submission-readiness errors. Present on every successful POST, PUT, and GET response. Empty means the application is ready to submit. Each entry has `code`, `message`, and optional `field`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HealthSherpa.OpenApiClient.Models.SubmissionReadinessError>? Errors { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HealthSherpa.OpenApiClient.Models.SubmissionReadinessError> Errors { get; set; }
#endif
        /// <summary>Audit timeline of the application lifecycle when available, ordered newest-first.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationEvent>? Events { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationEvent> Events { get; set; }
#endif
        /// <summary>The external_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalId { get; set; }
#nullable restore
#else
        public string ExternalId { get; set; }
#endif
        /// <summary>The issuer_hios_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IssuerHiosId { get; set; }
#nullable restore
#else
        public string IssuerHiosId { get; set; }
#endif
        /// <summary>State-aware actions the partner can currently take. HealthSherpa ONE generates `href` and `method` from `rel` so links point at public `/v1/enrollments` routes. POST and PUT actions still require the request bodies documented for those endpoints.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HealthSherpa.OpenApiClient.Models.NextAction>? NextActions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HealthSherpa.OpenApiClient.Models.NextAction> NextActions { get; set; }
#endif
        /// <summary>Carrier-reported payment status. Only present after submission; redirect carriers may not report it immediately.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationResponsePayment? Payment { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationResponsePayment Payment { get; set; }
#endif
        /// <summary>Carrier-specific payment guidance.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PaymentInstructions? PaymentInstructions { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PaymentInstructions PaymentInstructions { get; set; }
#endif
        /// <summary>The plan_hios_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlanHiosId { get; set; }
#nullable restore
#else
        public string PlanHiosId { get; set; }
#endif
        /// <summary>The plan_year property</summary>
        public int? PlanYear { get; set; }
        /// <summary>The policies property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetail>? Policies { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetail> Policies { get; set; }
#endif
        /// <summary>`draft` when the application has not yet been submitted. Transitions to `pending_effectuation` on successful submission. `submission_failed` means asynchronous carrier submission failed after submit returned.</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentResponsePolicyStatus? PolicyStatus { get; set; }
        /// <summary>The sep_reason property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SepReason { get; set; }
#nullable restore
#else
        public string SepReason { get; set; }
#endif
        /// <summary>The submitted_at property</summary>
        public DateTimeOffset? SubmittedAt { get; set; }
        /// <summary>Whether the carrier supports post-enrollment changes for this application. Only present on submitted applications.</summary>
        public bool? SupportsChanges { get; set; }
        /// <summary>The tpa_slug property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TpaSlug { get; set; }
#nullable restore
#else
        public string TpaSlug { get; set; }
#endif
        /// <summary>The updated_at property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentResponse"/> and sets the default values.
        /// </summary>
        public EnrollmentResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "application", n => { Application = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentResponseApplication>(global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentResponseApplication.CreateFromDiscriminatorValue); } },
                { "application_id", n => { ApplicationId = n.GetStringValue(); } },
                { "can_change_plan", n => { CanChangePlan = n.GetBoolValue(); } },
                { "can_report_change", n => { CanReportChange = n.GetBoolValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "desired_effective_date", n => { DesiredEffectiveDate = n.GetDateValue(); } },
                { "document_status", n => { DocumentStatus = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentResponseDocumentStatus>(); } },
                { "errors", n => { Errors = n.GetCollectionOfObjectValues<global::Soenneker.HealthSherpa.OpenApiClient.Models.SubmissionReadinessError>(global::Soenneker.HealthSherpa.OpenApiClient.Models.SubmissionReadinessError.CreateFromDiscriminatorValue)?.AsList(); } },
                { "events", n => { Events = n.GetCollectionOfObjectValues<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationEvent>(global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationEvent.CreateFromDiscriminatorValue)?.AsList(); } },
                { "external_id", n => { ExternalId = n.GetStringValue(); } },
                { "issuer_hios_id", n => { IssuerHiosId = n.GetStringValue(); } },
                { "next_actions", n => { NextActions = n.GetCollectionOfObjectValues<global::Soenneker.HealthSherpa.OpenApiClient.Models.NextAction>(global::Soenneker.HealthSherpa.OpenApiClient.Models.NextAction.CreateFromDiscriminatorValue)?.AsList(); } },
                { "payment", n => { Payment = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationResponsePayment>(global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationResponsePayment.CreateFromDiscriminatorValue); } },
                { "payment_instructions", n => { PaymentInstructions = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PaymentInstructions>(global::Soenneker.HealthSherpa.OpenApiClient.Models.PaymentInstructions.CreateFromDiscriminatorValue); } },
                { "plan_hios_id", n => { PlanHiosId = n.GetStringValue(); } },
                { "plan_year", n => { PlanYear = n.GetIntValue(); } },
                { "policies", n => { Policies = n.GetCollectionOfObjectValues<global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetail>(global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetail.CreateFromDiscriminatorValue)?.AsList(); } },
                { "policy_status", n => { PolicyStatus = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentResponsePolicyStatus>(); } },
                { "sep_reason", n => { SepReason = n.GetStringValue(); } },
                { "submitted_at", n => { SubmittedAt = n.GetDateTimeOffsetValue(); } },
                { "supports_changes", n => { SupportsChanges = n.GetBoolValue(); } },
                { "tpa_slug", n => { TpaSlug = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentResponseApplication>("application", Application);
            writer.WriteStringValue("application_id", ApplicationId);
            writer.WriteBoolValue("can_change_plan", CanChangePlan);
            writer.WriteBoolValue("can_report_change", CanReportChange);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteDateValue("desired_effective_date", DesiredEffectiveDate);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentResponseDocumentStatus>("document_status", DocumentStatus);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HealthSherpa.OpenApiClient.Models.SubmissionReadinessError>("errors", Errors);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationEvent>("events", Events);
            writer.WriteStringValue("external_id", ExternalId);
            writer.WriteStringValue("issuer_hios_id", IssuerHiosId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HealthSherpa.OpenApiClient.Models.NextAction>("next_actions", NextActions);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicationResponsePayment>("payment", Payment);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PaymentInstructions>("payment_instructions", PaymentInstructions);
            writer.WriteStringValue("plan_hios_id", PlanHiosId);
            writer.WriteIntValue("plan_year", PlanYear);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetail>("policies", Policies);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentResponsePolicyStatus>("policy_status", PolicyStatus);
            writer.WriteStringValue("sep_reason", SepReason);
            writer.WriteDateTimeOffsetValue("submitted_at", SubmittedAt);
            writer.WriteBoolValue("supports_changes", SupportsChanges);
            writer.WriteStringValue("tpa_slug", TpaSlug);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
