// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EnrollmentSessionApplicantIchra : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The employee_amount property</summary>
        public double? EmployeeAmount { get; set; }
        /// <summary>The family_amount property</summary>
        public double? FamilyAmount { get; set; }
        /// <summary>The offered property</summary>
        public bool? Offered { get; set; }
        /// <summary>The offered_cafeteria property</summary>
        public bool? OfferedCafeteria { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionApplicantIchra"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionApplicantIchra CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.EnrollmentSessionApplicantIchra();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "employee_amount", n => { EmployeeAmount = n.GetDoubleValue(); } },
                { "family_amount", n => { FamilyAmount = n.GetDoubleValue(); } },
                { "offered", n => { Offered = n.GetBoolValue(); } },
                { "offered_cafeteria", n => { OfferedCafeteria = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("employee_amount", EmployeeAmount);
            writer.WriteDoubleValue("family_amount", FamilyAmount);
            writer.WriteBoolValue("offered", Offered);
            writer.WriteBoolValue("offered_cafeteria", OfferedCafeteria);
        }
    }
}
#pragma warning restore CS0618
