// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExistingCoverage : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The has_existing_coverage property</summary>
        public bool? HasExistingCoverage { get; set; }
        /// <summary>The insurer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Insurer { get; set; }
#nullable restore
#else
        public string Insurer { get; set; }
#endif
        /// <summary>The plan_replaces_existing_coverage property</summary>
        public bool? PlanReplacesExistingCoverage { get; set; }
        /// <summary>The policyholder_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PolicyholderName { get; set; }
#nullable restore
#else
        public string PolicyholderName { get; set; }
#endif
        /// <summary>The policy_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PolicyId { get; set; }
#nullable restore
#else
        public string PolicyId { get; set; }
#endif
        /// <summary>The start_date property</summary>
        public Date? StartDate { get; set; }
        /// <summary>The term_date property</summary>
        public Date? TermDate { get; set; }
        /// <summary>`issuer`: coverage with another issuer. `government`: government program such as Medicare or Medicaid.</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.ExistingCoverageType? Type { get; set; }
        /// <summary>Whether the existing coverage will continue alongside the new plan.</summary>
        public bool? WillContinue { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.ExistingCoverage"/> and sets the default values.
        /// </summary>
        public ExistingCoverage()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.ExistingCoverage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.ExistingCoverage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.ExistingCoverage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "has_existing_coverage", n => { HasExistingCoverage = n.GetBoolValue(); } },
                { "insurer", n => { Insurer = n.GetStringValue(); } },
                { "plan_replaces_existing_coverage", n => { PlanReplacesExistingCoverage = n.GetBoolValue(); } },
                { "policy_id", n => { PolicyId = n.GetStringValue(); } },
                { "policyholder_name", n => { PolicyholderName = n.GetStringValue(); } },
                { "start_date", n => { StartDate = n.GetDateValue(); } },
                { "term_date", n => { TermDate = n.GetDateValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.ExistingCoverageType>(); } },
                { "will_continue", n => { WillContinue = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("has_existing_coverage", HasExistingCoverage);
            writer.WriteStringValue("insurer", Insurer);
            writer.WriteBoolValue("plan_replaces_existing_coverage", PlanReplacesExistingCoverage);
            writer.WriteStringValue("policyholder_name", PolicyholderName);
            writer.WriteStringValue("policy_id", PolicyId);
            writer.WriteDateValue("start_date", StartDate);
            writer.WriteDateValue("term_date", TermDate);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.ExistingCoverageType>("type", Type);
            writer.WriteBoolValue("will_continue", WillContinue);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
