// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>`issuer`: coverage with another issuer. `government`: government program such as Medicare or Medicaid.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ExistingCoverageType
    {
        [EnumMember(Value = "issuer")]
        #pragma warning disable CS1591
        Issuer,
        #pragma warning restore CS1591
        [EnumMember(Value = "government")]
        #pragma warning disable CS1591
        Government,
        #pragma warning restore CS1591
    }
}
