// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GuardianRelationship
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "parent")]
        #pragma warning disable CS1591
        Parent,
        #pragma warning restore CS1591
        [EnumMember(Value = "legal_guardian")]
        #pragma warning disable CS1591
        LegalGuardian,
        #pragma warning restore CS1591
        [EnumMember(Value = "grandparent")]
        #pragma warning disable CS1591
        Grandparent,
        #pragma warning restore CS1591
        [EnumMember(Value = "other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
    }
}
