// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>
    /// Required for primary applicants under 18.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Guardian : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alternate_phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlternatePhone { get; set; }
#nullable restore
#else
        public string AlternatePhone { get; set; }
#endif
        /// <summary>The date_of_birth property</summary>
        public Date? DateOfBirth { get; set; }
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The first_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>The gender property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.GuardianGender? Gender { get; set; }
        /// <summary>The home_phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HomePhone { get; set; }
#nullable restore
#else
        public string HomePhone { get; set; }
#endif
        /// <summary>The last_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>Guardian&apos;s mailing address, if different from the applicant&apos;s residential address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.GuardianMailingAddress? MailingAddress { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.GuardianMailingAddress MailingAddress { get; set; }
#endif
        /// <summary>The middle_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MiddleName { get; set; }
#nullable restore
#else
        public string MiddleName { get; set; }
#endif
        /// <summary>The relationship property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.GuardianRelationship? Relationship { get; set; }
        /// <summary>Required if `relationship` is `other`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RelationshipOther { get; set; }
#nullable restore
#else
        public string RelationshipOther { get; set; }
#endif
        /// <summary>The suffix property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.GuardianSuffix? Suffix { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.Guardian"/> and sets the default values.
        /// </summary>
        public Guardian()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.Guardian"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.Guardian CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.Guardian();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alternate_phone", n => { AlternatePhone = n.GetStringValue(); } },
                { "date_of_birth", n => { DateOfBirth = n.GetDateValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "first_name", n => { FirstName = n.GetStringValue(); } },
                { "gender", n => { Gender = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.GuardianGender>(); } },
                { "home_phone", n => { HomePhone = n.GetStringValue(); } },
                { "last_name", n => { LastName = n.GetStringValue(); } },
                { "mailing_address", n => { MailingAddress = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.GuardianMailingAddress>(global::Soenneker.HealthSherpa.OpenApiClient.Models.GuardianMailingAddress.CreateFromDiscriminatorValue); } },
                { "middle_name", n => { MiddleName = n.GetStringValue(); } },
                { "relationship", n => { Relationship = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.GuardianRelationship>(); } },
                { "relationship_other", n => { RelationshipOther = n.GetStringValue(); } },
                { "suffix", n => { Suffix = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.GuardianSuffix>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("alternate_phone", AlternatePhone);
            writer.WriteDateValue("date_of_birth", DateOfBirth);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("first_name", FirstName);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.GuardianGender>("gender", Gender);
            writer.WriteStringValue("home_phone", HomePhone);
            writer.WriteStringValue("last_name", LastName);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.GuardianMailingAddress>("mailing_address", MailingAddress);
            writer.WriteStringValue("middle_name", MiddleName);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.GuardianRelationship>("relationship", Relationship);
            writer.WriteStringValue("relationship_other", RelationshipOther);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.GuardianSuffix>("suffix", Suffix);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
