// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class HouseholdQuoteInput : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The annual_income property</summary>
        public double? AnnualIncome { get; set; }
        /// <summary>The applicants property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicantInput>? Applicants { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicantInput> Applicants { get; set; }
#endif
        /// <summary>The effective_date property</summary>
        public Date? EffectiveDate { get; set; }
        /// <summary>The household_size property</summary>
        public int? HouseholdSize { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.HouseholdQuoteInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.HouseholdQuoteInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.HouseholdQuoteInput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "annual_income", n => { AnnualIncome = n.GetDoubleValue(); } },
                { "applicants", n => { Applicants = n.GetCollectionOfObjectValues<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicantInput>(global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicantInput.CreateFromDiscriminatorValue)?.AsList(); } },
                { "effective_date", n => { EffectiveDate = n.GetDateValue(); } },
                { "household_size", n => { HouseholdSize = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("annual_income", AnnualIncome);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HealthSherpa.OpenApiClient.Models.ApplicantInput>("applicants", Applicants);
            writer.WriteDateValue("effective_date", EffectiveDate);
            writer.WriteIntValue("household_size", HouseholdSize);
        }
    }
}
#pragma warning restore CS0618
