// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>
    /// Health Reimbursement Arrangement details. Applies to the primary applicant, the employee receiving the HRA offer. If the ICHRA is affordable, all household members are ineligible for premium tax credits.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Hra : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Monthly contribution in USD.</summary>
        public float? Amount { get; set; }
        /// <summary>The annual_household_income property</summary>
        public float? AnnualHouseholdIncome { get; set; }
        /// <summary>The annual_household_income_determination property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnnualHouseholdIncomeDetermination { get; set; }
#nullable restore
#else
        public string AnnualHouseholdIncomeDetermination { get; set; }
#endif
        /// <summary>`premium`: premiums only. `premium_oop`: premiums and out-of-pocket costs.</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.HraContributionCovers? ContributionCovers { get; set; }
        /// <summary>The employer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.Employer? Employer { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.Employer Employer { get; set; }
#endif
        /// <summary>The household_size property</summary>
        public int? HouseholdSize { get; set; }
        /// <summary>`true`: applicant is offered an HRA. `false`: applicant is not offered an HRA. `null`: unknown.</summary>
        public bool? OfferedHra { get; set; }
        /// <summary>The premium_payer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PremiumPayer { get; set; }
#nullable restore
#else
        public string PremiumPayer { get; set; }
#endif
        /// <summary>The start property</summary>
        public Date? Start { get; set; }
        /// <summary>The type property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.HraType? Type { get; set; }
        /// <summary>Whether the HRA is used for spousal or family premiums. Relevant for QSEHRA 834 indicators.</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.HraUsedForSpousalOrFamilyPremiums? UsedForSpousalOrFamilyPremiums { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.Hra"/> and sets the default values.
        /// </summary>
        public Hra()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.Hra"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.Hra CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.Hra();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetFloatValue(); } },
                { "annual_household_income", n => { AnnualHouseholdIncome = n.GetFloatValue(); } },
                { "annual_household_income_determination", n => { AnnualHouseholdIncomeDetermination = n.GetStringValue(); } },
                { "contribution_covers", n => { ContributionCovers = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.HraContributionCovers>(); } },
                { "employer", n => { Employer = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.Employer>(global::Soenneker.HealthSherpa.OpenApiClient.Models.Employer.CreateFromDiscriminatorValue); } },
                { "household_size", n => { HouseholdSize = n.GetIntValue(); } },
                { "offered_hra", n => { OfferedHra = n.GetBoolValue(); } },
                { "premium_payer", n => { PremiumPayer = n.GetStringValue(); } },
                { "start", n => { Start = n.GetDateValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.HraType>(); } },
                { "used_for_spousal_or_family_premiums", n => { UsedForSpousalOrFamilyPremiums = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.HraUsedForSpousalOrFamilyPremiums>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteFloatValue("amount", Amount);
            writer.WriteFloatValue("annual_household_income", AnnualHouseholdIncome);
            writer.WriteStringValue("annual_household_income_determination", AnnualHouseholdIncomeDetermination);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.HraContributionCovers>("contribution_covers", ContributionCovers);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.Employer>("employer", Employer);
            writer.WriteIntValue("household_size", HouseholdSize);
            writer.WriteBoolValue("offered_hra", OfferedHra);
            writer.WriteStringValue("premium_payer", PremiumPayer);
            writer.WriteDateValue("start", Start);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.HraType>("type", Type);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.HraUsedForSpousalOrFamilyPremiums>("used_for_spousal_or_family_premiums", UsedForSpousalOrFamilyPremiums);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
