// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>`premium`: premiums only. `premium_oop`: premiums and out-of-pocket costs.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum HraContributionCovers
    {
        [EnumMember(Value = "premium")]
        #pragma warning disable CS1591
        Premium,
        #pragma warning restore CS1591
        [EnumMember(Value = "premium_oop")]
        #pragma warning disable CS1591
        PremiumOop,
        #pragma warning restore CS1591
    }
}
