// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum HraType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ichra")]
        #pragma warning disable CS1591
        Ichra,
        #pragma warning restore CS1591
        [EnumMember(Value = "qsehra")]
        #pragma warning disable CS1591
        Qsehra,
        #pragma warning restore CS1591
    }
}
