// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MedicalFilters : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The hsa_eligible property</summary>
        public bool? HsaEligible { get; set; }
        /// <summary>The metal_levels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HealthSherpa.OpenApiClient.Models.MedicalFiltersMetalLevelsItem?>? MetalLevels { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HealthSherpa.OpenApiClient.Models.MedicalFiltersMetalLevelsItem?> MetalLevels { get; set; }
#endif
        /// <summary>The plan_types property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HealthSherpa.OpenApiClient.Models.MedicalFiltersPlanTypesItem?>? PlanTypes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HealthSherpa.OpenApiClient.Models.MedicalFiltersPlanTypesItem?> PlanTypes { get; set; }
#endif
        /// <summary>The standardized_only property</summary>
        public bool? StandardizedOnly { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.MedicalFilters"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.MedicalFilters CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.MedicalFilters();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "hsa_eligible", n => { HsaEligible = n.GetBoolValue(); } },
                { "metal_levels", n => { MetalLevels = n.GetCollectionOfEnumValues<global::Soenneker.HealthSherpa.OpenApiClient.Models.MedicalFiltersMetalLevelsItem>()?.AsList(); } },
                { "plan_types", n => { PlanTypes = n.GetCollectionOfEnumValues<global::Soenneker.HealthSherpa.OpenApiClient.Models.MedicalFiltersPlanTypesItem>()?.AsList(); } },
                { "standardized_only", n => { StandardizedOnly = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("hsa_eligible", HsaEligible);
            writer.WriteCollectionOfEnumValues<global::Soenneker.HealthSherpa.OpenApiClient.Models.MedicalFiltersMetalLevelsItem>("metal_levels", MetalLevels);
            writer.WriteCollectionOfEnumValues<global::Soenneker.HealthSherpa.OpenApiClient.Models.MedicalFiltersPlanTypesItem>("plan_types", PlanTypes);
            writer.WriteBoolValue("standardized_only", StandardizedOnly);
        }
    }
}
#pragma warning restore CS0618
