// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>HTTP method to use.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum NextActionMethod
    {
        [EnumMember(Value = "GET")]
        #pragma warning disable CS1591
        Get,
        #pragma warning restore CS1591
        [EnumMember(Value = "PUT")]
        #pragma warning disable CS1591
        Put,
        #pragma warning restore CS1591
        [EnumMember(Value = "POST")]
        #pragma warning disable CS1591
        Post,
        #pragma warning restore CS1591
    }
}
