// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>Relation type identifying the action.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum NextActionRel
    {
        [EnumMember(Value = "self")]
        #pragma warning disable CS1591
        Self,
        #pragma warning restore CS1591
        [EnumMember(Value = "update")]
        #pragma warning disable CS1591
        Update,
        #pragma warning restore CS1591
        [EnumMember(Value = "validate")]
        #pragma warning disable CS1591
        Validate,
        #pragma warning restore CS1591
        [EnumMember(Value = "submit")]
        #pragma warning disable CS1591
        Submit,
        #pragma warning restore CS1591
        [EnumMember(Value = "cancel")]
        #pragma warning disable CS1591
        Cancel,
        #pragma warning restore CS1591
        [EnumMember(Value = "terminate")]
        #pragma warning disable CS1591
        Terminate,
        #pragma warning restore CS1591
        [EnumMember(Value = "payment_redirect")]
        #pragma warning disable CS1591
        PaymentRedirect,
        #pragma warning restore CS1591
        [EnumMember(Value = "upload_supporting_documentation")]
        #pragma warning disable CS1591
        UploadSupportingDocumentation,
        #pragma warning restore CS1591
        [EnumMember(Value = "change_plan")]
        #pragma warning disable CS1591
        ChangePlan,
        #pragma warning restore CS1591
    }
}
