// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>
    /// Carrier-specific payment guidance.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PaymentInstructions : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The pay_by_phone_supported property</summary>
        public bool? PayByPhoneSupported { get; set; }
        /// <summary>The payment_phone_number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentPhoneNumber { get; set; }
#nullable restore
#else
        public string PaymentPhoneNumber { get; set; }
#endif
        /// <summary>`true` when the carrier supports browser-based payment redirect.</summary>
        public bool? PaymentRedirectSupported { get; set; }
        /// <summary>`true` when payment must be set before submission. Currently applies to Cigna and Elevance in-flow.</summary>
        public bool? PaymentRequiredWithSubmission { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.PaymentInstructions"/> and sets the default values.
        /// </summary>
        public PaymentInstructions()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.PaymentInstructions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.PaymentInstructions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.PaymentInstructions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "pay_by_phone_supported", n => { PayByPhoneSupported = n.GetBoolValue(); } },
                { "payment_phone_number", n => { PaymentPhoneNumber = n.GetStringValue(); } },
                { "payment_redirect_supported", n => { PaymentRedirectSupported = n.GetBoolValue(); } },
                { "payment_required_with_submission", n => { PaymentRequiredWithSubmission = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("pay_by_phone_supported", PayByPhoneSupported);
            writer.WriteStringValue("payment_phone_number", PaymentPhoneNumber);
            writer.WriteBoolValue("payment_redirect_supported", PaymentRedirectSupported);
            writer.WriteBoolValue("payment_required_with_submission", PaymentRequiredWithSubmission);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
