// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>Present for medical quote results.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PlanQuoteResultDetailsMetalLevel
    {
        [EnumMember(Value = "bronze")]
        #pragma warning disable CS1591
        Bronze,
        #pragma warning restore CS1591
        [EnumMember(Value = "expanded_bronze")]
        #pragma warning disable CS1591
        ExpandedBronze,
        #pragma warning restore CS1591
        [EnumMember(Value = "silver")]
        #pragma warning disable CS1591
        Silver,
        #pragma warning restore CS1591
        [EnumMember(Value = "gold")]
        #pragma warning disable CS1591
        Gold,
        #pragma warning restore CS1591
        [EnumMember(Value = "platinum")]
        #pragma warning disable CS1591
        Platinum,
        #pragma warning restore CS1591
        [EnumMember(Value = "catastrophic")]
        #pragma warning disable CS1591
        Catastrophic,
        #pragma warning restore CS1591
    }
}
