// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PlanQuoteResult : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether this quoted plan passes the known plan, carrier, and state pre-create gates for direct off-exchange API enrollment at quote time. `true` means the plan can be used with the direct off-exchange enrollment API. `false` means use quote/display only or another enrollment path. This is not consumer ACA eligibility and does not guarantee successful submission after applicant and carrier validation.</summary>
        public bool? ApiEnrollable { get; set; }
        /// <summary>Resolved geographic availability lineage produced after county-first location resolution.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultAvailability? Availability { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultAvailability Availability { get; set; }
#endif
        /// <summary>The context property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultContext? Context { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultContext Context { get; set; }
#endif
        /// <summary>The coverage_family property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CoverageFamily { get; set; }
#nullable restore
#else
        public string CoverageFamily { get; set; }
#endif
        /// <summary>The coverage_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CoverageType { get; set; }
#nullable restore
#else
        public string CoverageType { get; set; }
#endif
        /// <summary>The details property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultDetails? Details { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultDetails Details { get; set; }
#endif
        /// <summary>The display_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>Canonical document slots. Carrier-specific source URLs are mapped into these stable fields.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultDocuments? Documents { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultDocuments Documents { get; set; }
#endif
        /// <summary>The external_plan_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalPlanId { get; set; }
#nullable restore
#else
        public string ExternalPlanId { get; set; }
#endif
        /// <summary>The issuer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultIssuer? Issuer { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultIssuer Issuer { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The network property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultNetwork? Network { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultNetwork Network { get; set; }
#endif
        /// <summary>The plan_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlanId { get; set; }
#nullable restore
#else
        public string PlanId { get; set; }
#endif
        /// <summary>The pricing property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultPricing? Pricing { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultPricing Pricing { get; set; }
#endif
        /// <summary>The release property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultRelease? Release { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultRelease Release { get; set; }
#endif
        /// <summary>The variant_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VariantId { get; set; }
#nullable restore
#else
        public string VariantId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResult"/> and sets the default values.
        /// </summary>
        public PlanQuoteResult()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_enrollable", n => { ApiEnrollable = n.GetBoolValue(); } },
                { "availability", n => { Availability = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultAvailability>(global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultAvailability.CreateFromDiscriminatorValue); } },
                { "context", n => { Context = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultContext>(global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultContext.CreateFromDiscriminatorValue); } },
                { "coverage_family", n => { CoverageFamily = n.GetStringValue(); } },
                { "coverage_type", n => { CoverageType = n.GetStringValue(); } },
                { "details", n => { Details = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultDetails>(global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultDetails.CreateFromDiscriminatorValue); } },
                { "display_name", n => { DisplayName = n.GetStringValue(); } },
                { "documents", n => { Documents = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultDocuments>(global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultDocuments.CreateFromDiscriminatorValue); } },
                { "external_plan_id", n => { ExternalPlanId = n.GetStringValue(); } },
                { "issuer", n => { Issuer = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultIssuer>(global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultIssuer.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "network", n => { Network = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultNetwork>(global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultNetwork.CreateFromDiscriminatorValue); } },
                { "plan_id", n => { PlanId = n.GetStringValue(); } },
                { "pricing", n => { Pricing = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultPricing>(global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultPricing.CreateFromDiscriminatorValue); } },
                { "release", n => { Release = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultRelease>(global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultRelease.CreateFromDiscriminatorValue); } },
                { "variant_id", n => { VariantId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("api_enrollable", ApiEnrollable);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultAvailability>("availability", Availability);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultContext>("context", Context);
            writer.WriteStringValue("coverage_family", CoverageFamily);
            writer.WriteStringValue("coverage_type", CoverageType);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultDetails>("details", Details);
            writer.WriteStringValue("display_name", DisplayName);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultDocuments>("documents", Documents);
            writer.WriteStringValue("external_plan_id", ExternalPlanId);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultIssuer>("issuer", Issuer);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultNetwork>("network", Network);
            writer.WriteStringValue("plan_id", PlanId);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultPricing>("pricing", Pricing);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultRelease>("release", Release);
            writer.WriteStringValue("variant_id", VariantId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
