// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PlanQuoteResultContextCoverageFamily
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "medical")]
        #pragma warning disable CS1591
        Medical,
        #pragma warning restore CS1591
        [EnumMember(Value = "ancillary")]
        #pragma warning disable CS1591
        Ancillary,
        #pragma warning restore CS1591
    }
}
