// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>
    /// Canonical document slots. Carrier-specific source URLs are mapped into these stable fields.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PlanQuoteResultDocuments : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The brochure_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BrochureUrl { get; set; }
#nullable restore
#else
        public string BrochureUrl { get; set; }
#endif
        /// <summary>The formulary_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FormularyUrl { get; set; }
#nullable restore
#else
        public string FormularyUrl { get; set; }
#endif
        /// <summary>The network_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NetworkUrl { get; set; }
#nullable restore
#else
        public string NetworkUrl { get; set; }
#endif
        /// <summary>Issuer-hosted page for making a premium payment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentUrl { get; set; }
#nullable restore
#else
        public string PaymentUrl { get; set; }
#endif
        /// <summary>Summary of Benefits and Coverage document URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SbcUrl { get; set; }
#nullable restore
#else
        public string SbcUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultDocuments"/> and sets the default values.
        /// </summary>
        public PlanQuoteResultDocuments()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultDocuments"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultDocuments CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultDocuments();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "brochure_url", n => { BrochureUrl = n.GetStringValue(); } },
                { "formulary_url", n => { FormularyUrl = n.GetStringValue(); } },
                { "network_url", n => { NetworkUrl = n.GetStringValue(); } },
                { "payment_url", n => { PaymentUrl = n.GetStringValue(); } },
                { "sbc_url", n => { SbcUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("brochure_url", BrochureUrl);
            writer.WriteStringValue("formulary_url", FormularyUrl);
            writer.WriteStringValue("network_url", NetworkUrl);
            writer.WriteStringValue("payment_url", PaymentUrl);
            writer.WriteStringValue("sbc_url", SbcUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
