// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PlanQuoteResultPricing : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The billing_period property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultPricingBillingPeriod? BillingPeriod { get; set; }
        /// <summary>The currency property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultPricingCurrency? Currency { get; set; }
        /// <summary>The ehb_premium property</summary>
        public double? EhbPremium { get; set; }
        /// <summary>The gross_premium property</summary>
        public double? GrossPremium { get; set; }
        /// <summary>The max_aptc property</summary>
        public double? MaxAptc { get; set; }
        /// <summary>The net_premium property</summary>
        public double? NetPremium { get; set; }
        /// <summary>The subsidy_applied property</summary>
        public double? SubsidyApplied { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultPricing"/> and sets the default values.
        /// </summary>
        public PlanQuoteResultPricing()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultPricing"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultPricing CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultPricing();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "billing_period", n => { BillingPeriod = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultPricingBillingPeriod>(); } },
                { "currency", n => { Currency = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultPricingCurrency>(); } },
                { "ehb_premium", n => { EhbPremium = n.GetDoubleValue(); } },
                { "gross_premium", n => { GrossPremium = n.GetDoubleValue(); } },
                { "max_aptc", n => { MaxAptc = n.GetDoubleValue(); } },
                { "net_premium", n => { NetPremium = n.GetDoubleValue(); } },
                { "subsidy_applied", n => { SubsidyApplied = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultPricingBillingPeriod>("billing_period", BillingPeriod);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PlanQuoteResultPricingCurrency>("currency", Currency);
            writer.WriteDoubleValue("ehb_premium", EhbPremium);
            writer.WriteDoubleValue("gross_premium", GrossPremium);
            writer.WriteDoubleValue("max_aptc", MaxAptc);
            writer.WriteDoubleValue("net_premium", NetPremium);
            writer.WriteDoubleValue("subsidy_applied", SubsidyApplied);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
