// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PlanQuoteResultDetailsType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "medical")]
        #pragma warning disable CS1591
        Medical,
        #pragma warning restore CS1591
        [EnumMember(Value = "dental")]
        #pragma warning disable CS1591
        Dental,
        #pragma warning restore CS1591
        [EnumMember(Value = "vision")]
        #pragma warning disable CS1591
        Vision,
        #pragma warning restore CS1591
        [EnumMember(Value = "supplemental_other")]
        #pragma warning disable CS1591
        SupplementalOther,
        #pragma warning restore CS1591
    }
}
