// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>Present for medical quote results.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PlanQuoteResultDetailsPlanType
    {
        [EnumMember(Value = "hmo")]
        #pragma warning disable CS1591
        Hmo,
        #pragma warning restore CS1591
        [EnumMember(Value = "ppo")]
        #pragma warning disable CS1591
        Ppo,
        #pragma warning restore CS1591
        [EnumMember(Value = "epo")]
        #pragma warning disable CS1591
        Epo,
        #pragma warning restore CS1591
        [EnumMember(Value = "pos")]
        #pragma warning disable CS1591
        Pos,
        #pragma warning restore CS1591
        [EnumMember(Value = "indemnity")]
        #pragma warning disable CS1591
        Indemnity,
        #pragma warning restore CS1591
    }
}
