// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>
    /// Marketplace policy status row for one policy attached to an application.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PolicyStatusItem : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Current balance in cents when returned by the Marketplace policy status API.</summary>
        public int? CurrentBalanceCents { get; set; }
        /// <summary>The effective_date property</summary>
        public Date? EffectiveDate { get; set; }
        /// <summary>The exchange_assigned_policy_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExchangeAssignedPolicyId { get; set; }
#nullable restore
#else
        public string ExchangeAssignedPolicyId { get; set; }
#endif
        /// <summary>The grace_period_start_date property</summary>
        public Date? GracePeriodStartDate { get; set; }
        /// <summary>The issuer_hios_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IssuerHiosId { get; set; }
#nullable restore
#else
        public string IssuerHiosId { get; set; }
#endif
        /// <summary>The paid_through_date property</summary>
        public Date? PaidThroughDate { get; set; }
        /// <summary>Past-due balance in cents when returned by the Marketplace policy status API.</summary>
        public int? PastDueBalanceCents { get; set; }
        /// <summary>The payment_status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentStatus { get; set; }
#nullable restore
#else
        public string PaymentStatus { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The updated_at property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyStatusItem"/> and sets the default values.
        /// </summary>
        public PolicyStatusItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyStatusItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyStatusItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyStatusItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "current_balance_cents", n => { CurrentBalanceCents = n.GetIntValue(); } },
                { "effective_date", n => { EffectiveDate = n.GetDateValue(); } },
                { "exchange_assigned_policy_id", n => { ExchangeAssignedPolicyId = n.GetStringValue(); } },
                { "grace_period_start_date", n => { GracePeriodStartDate = n.GetDateValue(); } },
                { "issuer_hios_id", n => { IssuerHiosId = n.GetStringValue(); } },
                { "paid_through_date", n => { PaidThroughDate = n.GetDateValue(); } },
                { "past_due_balance_cents", n => { PastDueBalanceCents = n.GetIntValue(); } },
                { "payment_status", n => { PaymentStatus = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("current_balance_cents", CurrentBalanceCents);
            writer.WriteDateValue("effective_date", EffectiveDate);
            writer.WriteStringValue("exchange_assigned_policy_id", ExchangeAssignedPolicyId);
            writer.WriteDateValue("grace_period_start_date", GracePeriodStartDate);
            writer.WriteStringValue("issuer_hios_id", IssuerHiosId);
            writer.WriteDateValue("paid_through_date", PaidThroughDate);
            writer.WriteIntValue("past_due_balance_cents", PastDueBalanceCents);
            writer.WriteStringValue("payment_status", PaymentStatus);
            writer.WriteStringValue("status", Status);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
