// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PolicyDetailStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "pending_effectuation")]
        #pragma warning disable CS1591
        PendingEffectuation,
        #pragma warning restore CS1591
        [EnumMember(Value = "effectuated")]
        #pragma warning disable CS1591
        Effectuated,
        #pragma warning restore CS1591
        [EnumMember(Value = "cancelled")]
        #pragma warning disable CS1591
        Cancelled,
        #pragma warning restore CS1591
        [EnumMember(Value = "terminated")]
        #pragma warning disable CS1591
        Terminated,
        #pragma warning restore CS1591
    }
}
