// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PolicyDetail : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The agent_of_record property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetailAgentOfRecord? AgentOfRecord { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetailAgentOfRecord AgentOfRecord { get; set; }
#endif
        /// <summary>The effective_date property</summary>
        public Date? EffectiveDate { get; set; }
        /// <summary>The expiration_date property</summary>
        public Date? ExpirationDate { get; set; }
        /// <summary>The gross_premium property</summary>
        public float? GrossPremium { get; set; }
        /// <summary>The members property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetailMembersItem>? Members { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetailMembersItem> Members { get; set; }
#endif
        /// <summary>Carrier-reported payment information. Fields are nullable because availability depends on carrier reporting.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyPaymentStatus? Payment { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyPaymentStatus Payment { get; set; }
#endif
        /// <summary>The plan_hios_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlanHiosId { get; set; }
#nullable restore
#else
        public string PlanHiosId { get; set; }
#endif
        /// <summary>The policy_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PolicyId { get; set; }
#nullable restore
#else
        public string PolicyId { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetailStatus? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetail"/> and sets the default values.
        /// </summary>
        public PolicyDetail()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetail"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetail CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetail();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agent_of_record", n => { AgentOfRecord = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetailAgentOfRecord>(global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetailAgentOfRecord.CreateFromDiscriminatorValue); } },
                { "effective_date", n => { EffectiveDate = n.GetDateValue(); } },
                { "expiration_date", n => { ExpirationDate = n.GetDateValue(); } },
                { "gross_premium", n => { GrossPremium = n.GetFloatValue(); } },
                { "members", n => { Members = n.GetCollectionOfObjectValues<global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetailMembersItem>(global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetailMembersItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "payment", n => { Payment = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyPaymentStatus>(global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyPaymentStatus.CreateFromDiscriminatorValue); } },
                { "plan_hios_id", n => { PlanHiosId = n.GetStringValue(); } },
                { "policy_id", n => { PolicyId = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetailStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetailAgentOfRecord>("agent_of_record", AgentOfRecord);
            writer.WriteDateValue("effective_date", EffectiveDate);
            writer.WriteDateValue("expiration_date", ExpirationDate);
            writer.WriteFloatValue("gross_premium", GrossPremium);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetailMembersItem>("members", Members);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyPaymentStatus>("payment", Payment);
            writer.WriteStringValue("plan_hios_id", PlanHiosId);
            writer.WriteStringValue("policy_id", PolicyId);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PolicyDetailStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
