// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>HTTP method to use. Always `POST`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostMethod
    {
        [EnumMember(Value = "POST")]
        #pragma warning disable CS1591
        Post,
        #pragma warning restore CS1591
    }
}
