// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>Required by some carriers. Use `decline_to_answer` if not collected.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PrimaryApplicantRaceEthnicity
    {
        [EnumMember(Value = "white")]
        #pragma warning disable CS1591
        White,
        #pragma warning restore CS1591
        [EnumMember(Value = "black_or_african_american")]
        #pragma warning disable CS1591
        BlackOrAfricanAmerican,
        #pragma warning restore CS1591
        [EnumMember(Value = "american_indian_or_alaskan_native")]
        #pragma warning disable CS1591
        AmericanIndianOrAlaskanNative,
        #pragma warning restore CS1591
        [EnumMember(Value = "asian_indian")]
        #pragma warning disable CS1591
        AsianIndian,
        #pragma warning restore CS1591
        [EnumMember(Value = "chinese")]
        #pragma warning disable CS1591
        Chinese,
        #pragma warning restore CS1591
        [EnumMember(Value = "filipino")]
        #pragma warning disable CS1591
        Filipino,
        #pragma warning restore CS1591
        [EnumMember(Value = "japanese")]
        #pragma warning disable CS1591
        Japanese,
        #pragma warning restore CS1591
        [EnumMember(Value = "korean")]
        #pragma warning disable CS1591
        Korean,
        #pragma warning restore CS1591
        [EnumMember(Value = "vietnamese")]
        #pragma warning disable CS1591
        Vietnamese,
        #pragma warning restore CS1591
        [EnumMember(Value = "native_hawaiian")]
        #pragma warning disable CS1591
        NativeHawaiian,
        #pragma warning restore CS1591
        [EnumMember(Value = "guamanian_or_chamorro")]
        #pragma warning disable CS1591
        GuamanianOrChamorro,
        #pragma warning restore CS1591
        [EnumMember(Value = "samoan")]
        #pragma warning disable CS1591
        Samoan,
        #pragma warning restore CS1591
        [EnumMember(Value = "decline_to_answer")]
        #pragma warning disable CS1591
        DeclineToAnswer,
        #pragma warning restore CS1591
    }
}
