// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PrimaryApplicantSuffix
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Jr.")]
        #pragma warning disable CS1591
        Jr,
        #pragma warning restore CS1591
        [EnumMember(Value = "Sr.")]
        #pragma warning disable CS1591
        Sr,
        #pragma warning restore CS1591
        [EnumMember(Value = "II")]
        #pragma warning disable CS1591
        Ii,
        #pragma warning restore CS1591
        [EnumMember(Value = "III")]
        #pragma warning disable CS1591
        Iii,
        #pragma warning restore CS1591
        [EnumMember(Value = "IV")]
        #pragma warning disable CS1591
        Iv,
        #pragma warning restore CS1591
        [EnumMember(Value = "V")]
        #pragma warning disable CS1591
        V,
        #pragma warning restore CS1591
    }
}
