// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>`male` and `female` are accepted by all carriers. `x` is accepted for New York applicants; carriers in other states reject `x` at submission.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PrimaryApplicantGender
    {
        [EnumMember(Value = "male")]
        #pragma warning disable CS1591
        Male,
        #pragma warning restore CS1591
        [EnumMember(Value = "female")]
        #pragma warning disable CS1591
        Female,
        #pragma warning restore CS1591
        [EnumMember(Value = "x")]
        #pragma warning disable CS1591
        X,
        #pragma warning restore CS1591
    }
}
