// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PrimaryApplicantPhoneType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "home")]
        #pragma warning disable CS1591
        Home,
        #pragma warning restore CS1591
        [EnumMember(Value = "work")]
        #pragma warning disable CS1591
        Work,
        #pragma warning restore CS1591
        [EnumMember(Value = "cell")]
        #pragma warning disable CS1591
        Cell,
        #pragma warning restore CS1591
    }
}
