// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>Required by some carriers. Use `decline_to_answer` if not collected.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PrimaryApplicantHispanicOrigin
    {
        [EnumMember(Value = "yes")]
        #pragma warning disable CS1591
        Yes,
        #pragma warning restore CS1591
        [EnumMember(Value = "no")]
        #pragma warning disable CS1591
        No,
        #pragma warning restore CS1591
        [EnumMember(Value = "decline_to_answer")]
        #pragma warning disable CS1591
        DeclineToAnswer,
        #pragma warning restore CS1591
    }
}
