// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class QuoteContext : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The coverage_family property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteContextCoverageFamily? CoverageFamily { get; set; }
        /// <summary>The coverage_type property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteContextCoverageType? CoverageType { get; set; }
        /// <summary>The exchange property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteContextExchange? Exchange { get; set; }
        /// <summary>The plan_year property</summary>
        public int? PlanYear { get; set; }
        /// <summary>The product property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteContextProduct? Product { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteContext"/> and sets the default values.
        /// </summary>
        public QuoteContext()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteContext"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteContext CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteContext();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "coverage_family", n => { CoverageFamily = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteContextCoverageFamily>(); } },
                { "coverage_type", n => { CoverageType = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteContextCoverageType>(); } },
                { "exchange", n => { Exchange = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteContextExchange>(); } },
                { "plan_year", n => { PlanYear = n.GetIntValue(); } },
                { "product", n => { Product = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteContextProduct>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteContextCoverageFamily>("coverage_family", CoverageFamily);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteContextCoverageType>("coverage_type", CoverageType);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteContextExchange>("exchange", Exchange);
            writer.WriteIntValue("plan_year", PlanYear);
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteContextProduct>("product", Product);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
