// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class QuoteFilters : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The effective_date property</summary>
        public Date? EffectiveDate { get; set; }
        /// <summary>The issuer_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? IssuerIds { get; set; }
#nullable restore
#else
        public List<string> IssuerIds { get; set; }
#endif
        /// <summary>The medical property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.MedicalFilters? Medical { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.MedicalFilters Medical { get; set; }
#endif
        /// <summary>The network_types property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? NetworkTypes { get; set; }
#nullable restore
#else
        public List<string> NetworkTypes { get; set; }
#endif
        /// <summary>The premium_max property</summary>
        public double? PremiumMax { get; set; }
        /// <summary>The premium_min property</summary>
        public double? PremiumMin { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteFilters"/> and sets the default values.
        /// </summary>
        public QuoteFilters()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteFilters"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteFilters CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteFilters();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "effective_date", n => { EffectiveDate = n.GetDateValue(); } },
                { "issuer_ids", n => { IssuerIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "medical", n => { Medical = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.MedicalFilters>(global::Soenneker.HealthSherpa.OpenApiClient.Models.MedicalFilters.CreateFromDiscriminatorValue); } },
                { "network_types", n => { NetworkTypes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "premium_max", n => { PremiumMax = n.GetDoubleValue(); } },
                { "premium_min", n => { PremiumMin = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateValue("effective_date", EffectiveDate);
            writer.WriteCollectionOfPrimitiveValues<string>("issuer_ids", IssuerIds);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.MedicalFilters>("medical", Medical);
            writer.WriteCollectionOfPrimitiveValues<string>("network_types", NetworkTypes);
            writer.WriteDoubleValue("premium_max", PremiumMax);
            writer.WriteDoubleValue("premium_min", PremiumMin);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
