// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>
    /// Canonical quote request for new integrations. Legacy `include` input is accepted for backward compatibility but ignored.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QuoteRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The context property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteContext? Context { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteContext Context { get; set; }
#endif
        /// <summary>The filters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteFilters? Filters { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteFilters Filters { get; set; }
#endif
        /// <summary>The household property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.HouseholdQuoteInput? Household { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.HouseholdQuoteInput Household { get; set; }
#endif
        /// <summary>Deprecated and ignored. Accepted for backward compatibility.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteRequestInclude? Include { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteRequestInclude Include { get; set; }
#endif
        /// <summary>The location property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.LocationInput? Location { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.LocationInput Location { get; set; }
#endif
        /// <summary>The page property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PageInput? Page { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.PageInput Page { get; set; }
#endif
        /// <summary>The sort property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.SortInput? Sort { get; set; }
#nullable restore
#else
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.SortInput Sort { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteRequest"/> and sets the default values.
        /// </summary>
        public QuoteRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "context", n => { Context = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteContext>(global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteContext.CreateFromDiscriminatorValue); } },
                { "filters", n => { Filters = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteFilters>(global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteFilters.CreateFromDiscriminatorValue); } },
                { "household", n => { Household = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.HouseholdQuoteInput>(global::Soenneker.HealthSherpa.OpenApiClient.Models.HouseholdQuoteInput.CreateFromDiscriminatorValue); } },
                { "include", n => { Include = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteRequestInclude>(global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteRequestInclude.CreateFromDiscriminatorValue); } },
                { "location", n => { Location = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.LocationInput>(global::Soenneker.HealthSherpa.OpenApiClient.Models.LocationInput.CreateFromDiscriminatorValue); } },
                { "page", n => { Page = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PageInput>(global::Soenneker.HealthSherpa.OpenApiClient.Models.PageInput.CreateFromDiscriminatorValue); } },
                { "sort", n => { Sort = n.GetObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.SortInput>(global::Soenneker.HealthSherpa.OpenApiClient.Models.SortInput.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteContext>("context", Context);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteFilters>("filters", Filters);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.HouseholdQuoteInput>("household", Household);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.QuoteRequestInclude>("include", Include);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.LocationInput>("location", Location);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.PageInput>("page", Page);
            writer.WriteObjectValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.SortInput>("sort", Sort);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
