// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ResponsiblePartyRelationship
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "parent_guardian")]
        #pragma warning disable CS1591
        ParentGuardian,
        #pragma warning restore CS1591
        [EnumMember(Value = "sibling")]
        #pragma warning disable CS1591
        Sibling,
        #pragma warning restore CS1591
    }
}
