// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Signatures : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The pediatric_dental_signature property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PediatricDentalSignature { get; set; }
#nullable restore
#else
        public string PediatricDentalSignature { get; set; }
#endif
        /// <summary>The pediatric_dental_signature_date property</summary>
        public Date? PediatricDentalSignatureDate { get; set; }
        /// <summary>Date the application was signed. Required for submission. This is separate from `applicants.primary.signature`, the typed name.</summary>
        public Date? SignatureDate { get; set; }
        /// <summary>State-required supplemental form disclosures signature for the primary applicant. Required for CO.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StateSupplementDisclosuresSignature { get; set; }
#nullable restore
#else
        public string StateSupplementDisclosuresSignature { get; set; }
#endif
        /// <summary>State-required supplemental form signature for the primary applicant. Required for CO, UT, NJ.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StateSupplementPrimarySignature { get; set; }
#nullable restore
#else
        public string StateSupplementPrimarySignature { get; set; }
#endif
        /// <summary>State-required supplemental form signature for spouse. Required for UT.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StateSupplementSpouseSignature { get; set; }
#nullable restore
#else
        public string StateSupplementSpouseSignature { get; set; }
#endif
        /// <summary>The translator_signature_date property</summary>
        public Date? TranslatorSignatureDate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.Signatures"/> and sets the default values.
        /// </summary>
        public Signatures()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.Signatures"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.Signatures CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.Signatures();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "pediatric_dental_signature", n => { PediatricDentalSignature = n.GetStringValue(); } },
                { "pediatric_dental_signature_date", n => { PediatricDentalSignatureDate = n.GetDateValue(); } },
                { "signature_date", n => { SignatureDate = n.GetDateValue(); } },
                { "state_supplement_disclosures_signature", n => { StateSupplementDisclosuresSignature = n.GetStringValue(); } },
                { "state_supplement_primary_signature", n => { StateSupplementPrimarySignature = n.GetStringValue(); } },
                { "state_supplement_spouse_signature", n => { StateSupplementSpouseSignature = n.GetStringValue(); } },
                { "translator_signature_date", n => { TranslatorSignatureDate = n.GetDateValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("pediatric_dental_signature", PediatricDentalSignature);
            writer.WriteDateValue("pediatric_dental_signature_date", PediatricDentalSignatureDate);
            writer.WriteDateValue("signature_date", SignatureDate);
            writer.WriteStringValue("state_supplement_disclosures_signature", StateSupplementDisclosuresSignature);
            writer.WriteStringValue("state_supplement_primary_signature", StateSupplementPrimarySignature);
            writer.WriteStringValue("state_supplement_spouse_signature", StateSupplementSpouseSignature);
            writer.WriteDateValue("translator_signature_date", TranslatorSignatureDate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
