// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>Standardized qualifying event type. HealthSherpa maps these to carrier-specific values automatically. `pregnancy` is accepted in CO, VA, NJ, and MD. For ICHRA enrollments, `offered_ichra` is the most common reason.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SpecialEnrollmentPeriodEventType
    {
        [EnumMember(Value = "birth")]
        #pragma warning disable CS1591
        Birth,
        #pragma warning restore CS1591
        [EnumMember(Value = "adoption")]
        #pragma warning disable CS1591
        Adoption,
        #pragma warning restore CS1591
        [EnumMember(Value = "death")]
        #pragma warning disable CS1591
        Death,
        #pragma warning restore CS1591
        [EnumMember(Value = "divorce")]
        #pragma warning disable CS1591
        Divorce,
        #pragma warning restore CS1591
        [EnumMember(Value = "marriage")]
        #pragma warning disable CS1591
        Marriage,
        #pragma warning restore CS1591
        [EnumMember(Value = "domestic_partnership")]
        #pragma warning disable CS1591
        DomesticPartnership,
        #pragma warning restore CS1591
        [EnumMember(Value = "child_support")]
        #pragma warning disable CS1591
        ChildSupport,
        #pragma warning restore CS1591
        [EnumMember(Value = "loss_of_mec")]
        #pragma warning disable CS1591
        LossOfMec,
        #pragma warning restore CS1591
        [EnumMember(Value = "loss_of_dependent")]
        #pragma warning disable CS1591
        LossOfDependent,
        #pragma warning restore CS1591
        [EnumMember(Value = "dependent_lost_coverage")]
        #pragma warning disable CS1591
        DependentLostCoverage,
        #pragma warning restore CS1591
        [EnumMember(Value = "loss_of_pregnancy_coverage")]
        #pragma warning disable CS1591
        LossOfPregnancyCoverage,
        #pragma warning restore CS1591
        [EnumMember(Value = "end_of_non_calendar_year_policy")]
        #pragma warning disable CS1591
        EndOfNonCalendarYearPolicy,
        #pragma warning restore CS1591
        [EnumMember(Value = "change_in_household_status")]
        #pragma warning disable CS1591
        ChangeInHouseholdStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "lost_aptc")]
        #pragma warning disable CS1591
        LostAptc,
        #pragma warning restore CS1591
        [EnumMember(Value = "relocation")]
        #pragma warning disable CS1591
        Relocation,
        #pragma warning restore CS1591
        [EnumMember(Value = "nj_county_change")]
        #pragma warning disable CS1591
        NjCountyChange,
        #pragma warning restore CS1591
        [EnumMember(Value = "offered_ichra")]
        #pragma warning disable CS1591
        OfferedIchra,
        #pragma warning restore CS1591
        [EnumMember(Value = "offered_qsehra")]
        #pragma warning disable CS1591
        OfferedQsehra,
        #pragma warning restore CS1591
        [EnumMember(Value = "mandated_covered_dependent")]
        #pragma warning disable CS1591
        MandatedCoveredDependent,
        #pragma warning restore CS1591
        [EnumMember(Value = "released_from_incarceration")]
        #pragma warning disable CS1591
        ReleasedFromIncarceration,
        #pragma warning restore CS1591
        [EnumMember(Value = "returning_active_duty")]
        #pragma warning disable CS1591
        ReturningActiveDuty,
        #pragma warning restore CS1591
        [EnumMember(Value = "provider_not_participating_in_prior_plan")]
        #pragma warning disable CS1591
        ProviderNotParticipatingInPriorPlan,
        #pragma warning restore CS1591
        [EnumMember(Value = "issuer_violated_contract")]
        #pragma warning disable CS1591
        IssuerViolatedContract,
        #pragma warning restore CS1591
        [EnumMember(Value = "misinformed")]
        #pragma warning disable CS1591
        Misinformed,
        #pragma warning restore CS1591
        [EnumMember(Value = "domestic_abuse")]
        #pragma warning disable CS1591
        DomesticAbuse,
        #pragma warning restore CS1591
        [EnumMember(Value = "family_care_app_ineligible")]
        #pragma warning disable CS1591
        FamilyCareAppIneligible,
        #pragma warning restore CS1591
        [EnumMember(Value = "pregnancy")]
        #pragma warning disable CS1591
        Pregnancy,
        #pragma warning restore CS1591
        [EnumMember(Value = "other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
    }
}
