// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>
    /// Submission-readiness error entry. Appears in the `errors[]` array of a successful enrollment response to indicate what must be completed before the application can be submitted.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubmissionReadinessError : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Machine-readable error code. Switch on this value instead of parsing `message`.</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.Models.SubmissionReadinessErrorCode? Code { get; set; }
        /// <summary>Dot-path to the offending field when the error is tied to a request field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Field { get; set; }
#nullable restore
#else
        public string Field { get; set; }
#endif
        /// <summary>Human-readable description of the error. May change over time.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.SubmissionReadinessError"/> and sets the default values.
        /// </summary>
        public SubmissionReadinessError()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.SubmissionReadinessError"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.SubmissionReadinessError CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.SubmissionReadinessError();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "code", n => { Code = n.GetEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.SubmissionReadinessErrorCode>(); } },
                { "field", n => { Field = n.GetStringValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.HealthSherpa.OpenApiClient.Models.SubmissionReadinessErrorCode>("code", Code);
            writer.WriteStringValue("field", Field);
            writer.WriteStringValue("message", Message);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
