// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    /// <summary>Machine-readable error code. Switch on this value instead of parsing `message`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SubmissionReadinessErrorCode
    {
        [EnumMember(Value = "unauthorized")]
        #pragma warning disable CS1591
        Unauthorized,
        #pragma warning restore CS1591
        [EnumMember(Value = "token_expired")]
        #pragma warning disable CS1591
        TokenExpired,
        #pragma warning restore CS1591
        [EnumMember(Value = "forbidden")]
        #pragma warning disable CS1591
        Forbidden,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_found")]
        #pragma warning disable CS1591
        NotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "plan_not_found")]
        #pragma warning disable CS1591
        PlanNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "plan_not_available")]
        #pragma warning disable CS1591
        PlanNotAvailable,
        #pragma warning restore CS1591
        [EnumMember(Value = "missing_required_field")]
        #pragma warning disable CS1591
        MissingRequiredField,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_field_value")]
        #pragma warning disable CS1591
        InvalidFieldValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_field_format")]
        #pragma warning disable CS1591
        InvalidFieldFormat,
        #pragma warning restore CS1591
        [EnumMember(Value = "internal_error")]
        #pragma warning disable CS1591
        InternalError,
        #pragma warning restore CS1591
        [EnumMember(Value = "rate_limit_exceeded")]
        #pragma warning disable CS1591
        RateLimitExceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "payload_too_large")]
        #pragma warning disable CS1591
        PayloadTooLarge,
        #pragma warning restore CS1591
        [EnumMember(Value = "duplicate_external_id")]
        #pragma warning disable CS1591
        DuplicateExternalId,
        #pragma warning restore CS1591
        [EnumMember(Value = "latest_submission_failed")]
        #pragma warning disable CS1591
        LatestSubmissionFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "supporting_documentation_required")]
        #pragma warning disable CS1591
        SupportingDocumentationRequired,
        #pragma warning restore CS1591
        [EnumMember(Value = "ineligible_for_enrollment")]
        #pragma warning disable CS1591
        IneligibleForEnrollment,
        #pragma warning restore CS1591
    }
}
