// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class VisionFilters : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The contacts_allowance_min property</summary>
        public double? ContactsAllowanceMin { get; set; }
        /// <summary>The exam_copay_max property</summary>
        public double? ExamCopayMax { get; set; }
        /// <summary>The frames_allowance_min property</summary>
        public double? FramesAllowanceMin { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.VisionFilters"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HealthSherpa.OpenApiClient.Models.VisionFilters CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HealthSherpa.OpenApiClient.Models.VisionFilters();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "contacts_allowance_min", n => { ContactsAllowanceMin = n.GetDoubleValue(); } },
                { "exam_copay_max", n => { ExamCopayMax = n.GetDoubleValue(); } },
                { "frames_allowance_min", n => { FramesAllowanceMin = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("contacts_allowance_min", ContactsAllowanceMin);
            writer.WriteDoubleValue("exam_copay_max", ExamCopayMax);
            writer.WriteDoubleValue("frames_allowance_min", FramesAllowanceMin);
        }
    }
}
#pragma warning restore CS0618
