// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.HealthSherpa.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.V1.Enrollments.Item.Payment_redirect
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\enrollments\{enrollmentId}\payment_redirect
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Payment_redirectRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.V1.Enrollments.Item.Payment_redirect.Payment_redirectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Payment_redirectRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/enrollments/{enrollmentId}/payment_redirect?exchange={exchange}&product={product}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.V1.Enrollments.Item.Payment_redirect.Payment_redirectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Payment_redirectRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/enrollments/{enrollmentId}/payment_redirect?exchange={exchange}&product={product}", rawUrl)
        {
        }
        /// <summary>
        /// Approval-gated direct enrollment API for retrieving the carrier payment redirect data for an off-exchange application. Send `product=ichra` and `exchange=off_exchange` as required query parameters so HealthSherpa ONE can validate the direct-enrollment routing channel. Use this when the application response includes `payment_instructions.payment_redirect_supported = true`.The response includes the carrier endpoint URL, the HTTP method, and form fields to submit in the shopper&apos;s browser. The keys and values in `fields` vary by carrier. Do not interpret, filter, rename, or modify them; include every returned field exactly as provided as hidden inputs in a form POST to `endpoint`. Service failures are returned as a top-level `errors[]` array with `code`, `message`, and optional `field`; failures blocked at the API edge use the unified `error` envelope.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.PaymentRedirectResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.ErrorResponse">When receiving a 502 status code</exception>
        /// <exception cref="global::Soenneker.HealthSherpa.OpenApiClient.Models.ErrorResponse">When receiving a 504 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.HealthSherpa.OpenApiClient.Models.PaymentRedirectResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.HealthSherpa.OpenApiClient.V1.Enrollments.Item.Payment_redirect.Payment_redirectRequestBuilder.Payment_redirectRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.HealthSherpa.OpenApiClient.Models.PaymentRedirectResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.HealthSherpa.OpenApiClient.V1.Enrollments.Item.Payment_redirect.Payment_redirectRequestBuilder.Payment_redirectRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "502", global::Soenneker.HealthSherpa.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "504", global::Soenneker.HealthSherpa.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.HealthSherpa.OpenApiClient.Models.PaymentRedirectResponse>(requestInfo, global::Soenneker.HealthSherpa.OpenApiClient.Models.PaymentRedirectResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Approval-gated direct enrollment API for retrieving the carrier payment redirect data for an off-exchange application. Send `product=ichra` and `exchange=off_exchange` as required query parameters so HealthSherpa ONE can validate the direct-enrollment routing channel. Use this when the application response includes `payment_instructions.payment_redirect_supported = true`.The response includes the carrier endpoint URL, the HTTP method, and form fields to submit in the shopper&apos;s browser. The keys and values in `fields` vary by carrier. Do not interpret, filter, rename, or modify them; include every returned field exactly as provided as hidden inputs in a form POST to `endpoint`. Service failures are returned as a top-level `errors[]` array with `code`, `message`, and optional `field`; failures blocked at the API edge use the unified `error` envelope.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.HealthSherpa.OpenApiClient.V1.Enrollments.Item.Payment_redirect.Payment_redirectRequestBuilder.Payment_redirectRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.HealthSherpa.OpenApiClient.V1.Enrollments.Item.Payment_redirect.Payment_redirectRequestBuilder.Payment_redirectRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HealthSherpa.OpenApiClient.V1.Enrollments.Item.Payment_redirect.Payment_redirectRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.HealthSherpa.OpenApiClient.V1.Enrollments.Item.Payment_redirect.Payment_redirectRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.HealthSherpa.OpenApiClient.V1.Enrollments.Item.Payment_redirect.Payment_redirectRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Approval-gated direct enrollment API for retrieving the carrier payment redirect data for an off-exchange application. Send `product=ichra` and `exchange=off_exchange` as required query parameters so HealthSherpa ONE can validate the direct-enrollment routing channel. Use this when the application response includes `payment_instructions.payment_redirect_supported = true`.The response includes the carrier endpoint URL, the HTTP method, and form fields to submit in the shopper&apos;s browser. The keys and values in `fields` vary by carrier. Do not interpret, filter, rename, or modify them; include every returned field exactly as provided as hidden inputs in a form POST to `endpoint`. Service failures are returned as a top-level `errors[]` array with `code`, `message`, and optional `field`; failures blocked at the API edge use the unified `error` envelope.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Payment_redirectRequestBuilderGetQueryParameters 
        {
            /// <summary>Direct-enrollment routing channel. Must be `off_exchange`.</summary>
            [QueryParameter("exchange")]
            public global::Soenneker.HealthSherpa.OpenApiClient.Models.OffExchangeExchange? Exchange { get; set; }
            /// <summary>Direct-enrollment product. Must be `ichra`.</summary>
            [QueryParameter("product")]
            public global::Soenneker.HealthSherpa.OpenApiClient.Models.IchraProduct? Product { get; set; }
        }
    }
}
#pragma warning restore CS0618
