// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.HealthSherpa.OpenApiClient.V1.EnrollmentSessions;
using Soenneker.HealthSherpa.OpenApiClient.V1.Enrollments;
using Soenneker.HealthSherpa.OpenApiClient.V1.Ping;
using Soenneker.HealthSherpa.OpenApiClient.V1.PolicyStatus;
using Soenneker.HealthSherpa.OpenApiClient.V1.Quotes;
using Soenneker.HealthSherpa.OpenApiClient.V1.Reference;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The enrollments property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.V1.Enrollments.EnrollmentsRequestBuilder Enrollments
        {
            get => new global::Soenneker.HealthSherpa.OpenApiClient.V1.Enrollments.EnrollmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The enrollmentSessions property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.V1.EnrollmentSessions.EnrollmentSessionsRequestBuilder EnrollmentSessions
        {
            get => new global::Soenneker.HealthSherpa.OpenApiClient.V1.EnrollmentSessions.EnrollmentSessionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ping property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.V1.Ping.PingRequestBuilder Ping
        {
            get => new global::Soenneker.HealthSherpa.OpenApiClient.V1.Ping.PingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The policyStatus property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.V1.PolicyStatus.PolicyStatusRequestBuilder PolicyStatus
        {
            get => new global::Soenneker.HealthSherpa.OpenApiClient.V1.PolicyStatus.PolicyStatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The quotes property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.V1.Quotes.QuotesRequestBuilder Quotes
        {
            get => new global::Soenneker.HealthSherpa.OpenApiClient.V1.Quotes.QuotesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reference property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.V1.Reference.ReferenceRequestBuilder Reference
        {
            get => new global::Soenneker.HealthSherpa.OpenApiClient.V1.Reference.ReferenceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
