// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.HealthSherpa.OpenApiClient.V1.Reference.Counties;
using Soenneker.HealthSherpa.OpenApiClient.V1.Reference.Issuers;
using Soenneker.HealthSherpa.OpenApiClient.V1.Reference.Providers;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.HealthSherpa.OpenApiClient.V1.Reference
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\reference
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReferenceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The counties property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.V1.Reference.Counties.CountiesRequestBuilder Counties
        {
            get => new global::Soenneker.HealthSherpa.OpenApiClient.V1.Reference.Counties.CountiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The issuers property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.V1.Reference.Issuers.IssuersRequestBuilder Issuers
        {
            get => new global::Soenneker.HealthSherpa.OpenApiClient.V1.Reference.Issuers.IssuersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The providers property</summary>
        public global::Soenneker.HealthSherpa.OpenApiClient.V1.Reference.Providers.ProvidersRequestBuilder Providers
        {
            get => new global::Soenneker.HealthSherpa.OpenApiClient.V1.Reference.Providers.ProvidersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.V1.Reference.ReferenceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReferenceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/reference", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HealthSherpa.OpenApiClient.V1.Reference.ReferenceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReferenceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/reference", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
